In [58]:
import numpy as np

A = np.array([
    [3., -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

A

array([[ 3., -3., -4.],
       [ 1., -1., -1.],
       [ 2., -1.,  4.]])

In [59]:
np.linalg.eig(A)

(array([ 3.03248022+2.48958756j,  3.03248022-2.48958756j,
        -0.06496045+0.j        ]),
 array([[ 0.81800407+0.j        ,  0.81800407-0.j        ,
         -0.61677134+0.j        ],
        [ 0.23416349-0.02249742j,  0.23416349+0.02249742j,
         -0.7791653 +0.j        ],
        [-0.18226486-0.49225013j, -0.18226486+0.49225013j,
          0.11177904+0.j        ]]))

In [81]:
import numpy as np

A = np.array([
    [3., 3, 4],
    [1, 1, -1],
    [2, 1, 4],
])

np.linalg.eig(A)

(array([ 6.4313753 , -0.52089263,  2.08951733]),
 array([[-0.76735724, -0.75533823, -0.20982171],
        [-0.02330182,  0.62539479, -0.75866959],
        [-0.6407963 ,  0.1958201 ,  0.61676195]]))

In [65]:
import numpy as np

A = np.array([
    [2., 3],
    [4, 1],
])

np.linalg.eig(A)

(array([ 5., -2.]),
 array([[ 0.70710678, -0.6       ],
        [ 0.70710678,  0.8       ]]))

In [66]:
0.8/.6

1.3333333333333335

In [67]:
4/3

1.3333333333333333

In [68]:
import numpy as np

A = np.array([
    [2., 7],
    [5, -9],
])

np.linalg.eig(A)

(array([  4.57774721, -11.57774721]),
 array([[ 0.9383953 , -0.45823608],
        [ 0.34556369,  0.88883052]]))

In [71]:
from sympy import *

M = Matrix([
    [2., 7],
    [5, -9],
])

M.eigenvals()


{4.57774721070176: 1, -11.5777472107018: 1}

In [72]:
M.eigenvects()


[(4.57774721070176,
  1,
  [Matrix([
   [0.938395296916184],
   [0.345563694165906]])]),
 (-11.5777472107018,
  1,
  [Matrix([
   [-0.461734115502309],
   [ 0.895615585549618]])])]

In [70]:
from sympy import *

M = Matrix([
    [3., -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

M

Matrix([
[3.0, -3, -4],
[  1, -1, -1],
[  2, -1,  4]])

In [20]:
M.det()

-1.00000000000000

In [21]:
Eiv = M.eigenvals()
Eiv

{-0.0649604478220922 - 9.46733982568332e-64*I: 1,
 3.03248022391105 - 2.48958756389532*I: 1,
 3.03248022391105 + 2.48958756389532*I: 1}

In [22]:
Eivec = M.eigenvects()
Eivec

[(-0.0649604478220922 - 9.46733982568332e-64*I,
  1,
  [Matrix([
   [  0.605929384171092 + 0.115136709162195*I],
   [  0.765468697581534 + 0.145451844899015*I],
   [-0.109814124021752 - 0.0208665187556304*I]])]),
 (3.03248022391105 - 2.48958756389532*I,
  1,
  [Matrix([
   [0.902070608999798 - 0.721023165140121*I],
   [0.278058713304286 - 0.181592058671222*I],
   [ 0.232893677484134 + 0.70349473494596*I]])]),
 (3.03248022391105 + 2.48958756389532*I,
  1,
  [Matrix([
   [ -0.539953240139931 + 1.02081158239527*I],
   [-0.126492906813434 + 0.307069810210603*I],
   [0.734604085798276 + 0.0974738130845893*I]])])]

In [38]:
x = symbols('x')
solveset(-x**3 + 14.0*x**2 -35*x + 22, x)

{1.0, 2.0, 11.0}

In [47]:
import numpy as np 

p = np.polynomial.Polynomial([22,-35,14,-1])
p

Polynomial([ 22., -35.,  14.,  -1.], domain=[-1,  1], window=[-1,  1])

In [52]:
np.polynomial.polynomial.polyroots(p.coef)

array([ 1.,  2., 11.])

In [50]:
p.roots()

array([ 1.,  2., 11.])

In [42]:
p2 = np.polynomial.polynomial.polyfromroots([1,2,11])
p2

array([-22.,  35., -14.,   1.])

In [43]:
np.polynomial.polynomial.polyroots(p2)

array([ 1.,  2., 11.])

In [18]:
import numpy as np

A = np.array([
    [2., 3],
    [4, 1],
])

evv = np.linalg.eig(A)
evv

(array([ 5., -2.]),
 array([[ 0.70710678, -0.6       ],
        [ 0.70710678,  0.8       ]]))

In [22]:
import numpy as np

v1 = 5
v2 = -2

I = np.identity(2)

E1 = A - v1*I
E2 = A - v2*I

E1, E2

(array([[-3.,  3.],
        [ 4., -4.]]),
 array([[4., 3.],
        [4., 3.]]))

In [23]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [6]:
E @ b

array([[0.],
       [0.]])

In [28]:
M = np.copy(E1)
m,n = M.shape
P = m-1

for p in range(P):
    print(M)
    for i in range(p+1,m):
        M[i] = M[i] - M[p]*M[i,p]/M[p,p]
        print(M)
        
    

[[-3.  3.]
 [ 4. -4.]]
[[-3.  3.]
 [ 0.  0.]]


In [24]:
M = np.copy(E2)
m,n = M.shape
P = m-1

for p in range(P):
    print(M)
    for i in range(p+1,m):
        M[i] = M[i] - M[p]*M[i,p]/M[p,p]
        print(M)
        
    

[[4. 3.]
 [4. 3.]]
[[4. 3.]
 [0. 0.]]


In [29]:
M = np.array([[-3,3],
              [4,3]])

m,n = M.shape
P = m-1

for p in range(P):
    print(M)
    for i in range(p+1,m):
        M[i] = M[i] - M[p]*M[i,p]/M[p,p]
        print(M)


[[-3  3]
 [ 4  3]]
[[-3  3]
 [ 0  7]]
