In [ ]:
import numpy as np

A = np.array([
    [-1, 2, 4, 7, 8],
    [1, 0, 5, -2, 8],
    [0, 2, -4, 7, 8],
    [2, 0, 3, 7, 8],
    [3, 3, 4, 0, 8],
])

b = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
])


In [56]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
a1 = np.trunc(a)
a2 = abs(a-a1)
a2 > 1

abs(a) % 1

array([0.7, 0.5, 0.2, 0.2, 0.5, 0.7, 0. ])

In [52]:
a = np.array([0.0, 0.0, 0.0])
a == 0

array([ True,  True,  True])

In [11]:
import numpy as np

for i in range(2000000):
    
    A = np.random.randint(-9,9,(5,5))
    
    if np.linalg.det(A) == 0:
        continue;
    
    
    b = np.random.randint(-12,12,(5,1))

    # M = np.concatenate((A, b), axis=1)

    # print()
    # print("M = \n", M)

    x = np.linalg.solve(A, b)
    
    x2 = abs(x)%1
    if (x2 == 0).all() == False:
        continue    

    # print("run ", i+1)
        
    # print("A = \n", A)
    # print()
    # print("b = \n", b)

    # print()
    # print("x = \n", x)
    
    # get 3x3
    E = A[:3, : 3]

    # eigen
    ei_val, ei_vec = np.linalg.eig(E)
    
    if(np.iscomplex(ei_val).any() or np.iscomplex(ei_vec).any()):
        continue;
    
    else:    
        a = ei_val
        # a1 = np.trunc(a)
        # a2 = abs(a-a1)
        a2 = abs(a) % 1
        
        if (a2 == 0).all() == False:
            continue
        
        print("run ", i+1)
        
        print("A = \n", A)
        print()
        print("b = \n", b)

        print()
        print("x = \n", x)

        print()
        print("E = \n", E)
        
        print()
        print("eigen-values = \n", ei_val)

        print()
        print("eigen-vectors = \n", ei_vec)
        
        print("/////////////////////////////////////////////////////")
        # break
        


In [7]:
print(x)
x2 = abs(x)%1
print(x2)
x2 == 0

[[-2.35383065]
 [ 2.25100806]
 [ 0.28629032]
 [ 0.74798387]
 [-0.62197581]]
[[0.35383065]
 [0.25100806]
 [0.28629032]
 [0.74798387]
 [0.62197581]]


array([[False],
       [False],
       [False],
       [False],
       [False]])

In [39]:
c = np.array([1, 2+2j],)
if(np.iscomplex(c).any() == True):
    print("complex")
    
c.dtype
np.iscomplex(c)


complex


array([False,  True])

In [38]:
np.iscomplex(c).any()

True

In [ ]:

print()
print("eigen-values = \n", ei_val)

print()
print("eigen-vectors = \n", ei_vec)

for i in range(len(ei_val)):
    print()
    print("eigen-value = ", ei_val[i])
    print()
    print("eigen-vector = \n", ei_vec[:,i])
    


In [ ]:
from sympy import *

AA = Matrix((
    (-1, 2, 4, 7, 8),
    (1, 0, 5, -2, 8),
    (0, 2, -4, 7, 8),
    (2, 0, 3, 7, 8),
    (3, 3, 4, 0, 8),
))

bb = Matrix((
    (1),
    (2),
    (3),
    (4),
    (5),
))

MM = AA.col_insert(5, bb)

v, w, x, y, z = symbols('v,w,x,y,z')

system = MM[:, :-1], MM[:, -1]

linsolve(system, v, w, x, y, z)


In [ ]:
MM.rref()


In [ ]:
EE = MM[:3, :3]

EE


In [ ]:
EE.eigenvals()


In [ ]:
EE.eigenvects()


In [ ]:
EE[0, 0] = -1.0


In [ ]:
EE


In [ ]:
EE.eigenvals()


In [ ]:
EE.eigenvects()
