$$
A=\left[
    \begin{matrix}
        1 & -1 & -1 & 1 \\ 
        3 & 1 & 1 & -4 \\ 
        -2 & 1 & -5 & 1 \\ 
        3 & 1 & -2 & -1 \\ 
    \end{matrix}
    \right]	
$$

$$
b=\left[
    \begin{matrix}
        1  \\ 
        2  \\ 
        -3  \\ 
        4  \\ 
    \end{matrix}
    \right]	
$$

$$
\left[
    \begin{matrix}
        1 & -1 & -1 & 1 \\ 
        3 & 1 & 1 & -4 \\ 
        -2 & 1 & -5 & 1 \\ 
        3 & 1 & -2 & -1 \\ 
    \end{matrix}
    \right]	
\left[
    \begin{matrix}
        a \\ 
        b \\ 
        c \\ 
        d \\ 
    \end{matrix}
    \right]	
=
\left[
    \begin{matrix}
        1 \\ 
        2 \\ 
        -3 \\ 
        4 \\ 
    \end{matrix}
    \right]	
$$

In [1]:
import numpy as np

A = np.array(
    [
        [1, -1, -1, 1],
        [3, 1, 1, -4],
        [-2, 1, -5, 1],
        [3, 1, -2, -1],
    ], dtype=float
)

b = np.array(
    [
        [1],
        [2],
        [-3],
        [4],
    ], dtype=float
)

In [2]:
import numpy as np

(m,n) = np.shape(A)
print('order of A=\n', A, '= ', f'{m} x {n}')

order of A=
 [[ 1. -1. -1.  1.]
 [ 3.  1.  1. -4.]
 [-2.  1. -5.  1.]
 [ 3.  1. -2. -1.]] =  4 x 4


$$
A=
\left[
    \begin{matrix}
        1 & -1 & -1 & 1 \\ 
        3 & 1 & 1 & -4 \\ 
        -2 & 1 & -5 & 1 \\ 
        3 & 1 & -2 & -1 \\ 
    \end{matrix}
    \right]	
= 4 \times 4
$$

In [3]:
import numpy as np

(m,n) = np.shape(b)
print('order of b= \n', b, '= ', f'{m} x {n}')

order of b= 
 [[ 1.]
 [ 2.]
 [-3.]
 [ 4.]] =  4 x 1


$$ 
b=
\left[
    \begin{matrix}
        1 \\ 
        2 \\ 
        -3 \\ 
        4 \\ 
    \end{matrix}
    \right]	
= 4 \times 1
$$

$$
A_b=[A|b]=\left[
    \begin{matrix}
        1 & -1 & -1 & 1 & | & 1 \\ 
        3 & 1 & 1 & -4 & | & 2 \\ 
        -2 & 1 & -5 & 1 & | & -3 \\ 
        3 & 1 & -2 & -1 & | & 4 \\ 
    \end{matrix}
    \right]	
$$

$$
A_b=\left[
    \begin{matrix}
        1 & -1 & -1 & 1 & | & 1 \\ 
        3 & 1 & 1 & -4 & | & 2 \\ 
        -2 & 1 & -5 & 1 & | & -3 \\ 
        3 & 1 & -2 & -1 & | & 4 \\ 
    \end{matrix}
    \right]	
= 4 \times 5
$$

In [4]:
x = np.linalg.solve(A,b)

print('x = \n', x)


x = 
 [[1.57894737]
 [1.24561404]
 [0.43859649]
 [1.10526316]]


In [5]:
from sympy import *

x1, x2, x3, x4 =symbols('a b c d')

linsolve(
    Matrix(
        (
           [1, -1, -1, 1, 1],
            [3, 1, 1, -4, 2],
            [-2, 1, -5, 1, -3],
            [3, 1, -2, -1, 4],
        )
    ), 
    (x1, x2, x3, x4)
)


FiniteSet((30/19, 71/57, 25/57, 21/19))

In [6]:
import numpy as np
from fractions import Fraction

# M = np.array(
#     [
#         [1, -1, -1, 1, 1],
#         [3, 1, 1, -4, 2],
#         [-2, 1, -5, 1, -3],
#         [3, 1, -2, -1, 4],
#     ],dtype=float
# )
M = np.append(A,b, axis=1)

print('M =\n', M)
(m,n) = M.shape
print('mxn = ', m, 'x', n)
print('A = \n', M[:m,:m])
print('|A| = ', np.linalg.det(M[:m,:m]))
print('rank(A) = ', np.linalg.matrix_rank(M[:m,:m]))

k = 0
p = 0

for p in range(0,m-1):
    for i in range(p+1,m):
        if M[p,p] == 0:
            # change row
            for j in range(i,m):
                if M[j,p] != 0:
                    k += 1
                    Mp = np.copy(M[p])
                    M[p] = M[j]
                    M[j] = Mp

                    print('Mx =\n', M)
                    break

        M[i] = M[i,:] - M[p,:]*M[i,p]/M[p,p]
        print(f'p = {p+1}, i={i+1}')
        print('M =\n', M)

detA =1
for p in range(0,m):
    detA *= M[p,p]

print('|A| =', detA)

M =
 [[ 1. -1. -1.  1.  1.]
 [ 3.  1.  1. -4.  2.]
 [-2.  1. -5.  1. -3.]
 [ 3.  1. -2. -1.  4.]]
mxn =  4 x 5
A = 
 [[ 1. -1. -1.  1.]
 [ 3.  1.  1. -4.]
 [-2.  1. -5.  1.]
 [ 3.  1. -2. -1.]]
|A| =  -57.00000000000001
rank(A) =  4
p = 1, i=2
M =
 [[ 1. -1. -1.  1.  1.]
 [ 0.  4.  4. -7. -1.]
 [-2.  1. -5.  1. -3.]
 [ 3.  1. -2. -1.  4.]]
p = 1, i=3
M =
 [[ 1. -1. -1.  1.  1.]
 [ 0.  4.  4. -7. -1.]
 [ 0. -1. -7.  3. -1.]
 [ 3.  1. -2. -1.  4.]]
p = 1, i=4
M =
 [[ 1. -1. -1.  1.  1.]
 [ 0.  4.  4. -7. -1.]
 [ 0. -1. -7.  3. -1.]
 [ 0.  4.  1. -4.  1.]]
p = 2, i=3
M =
 [[ 1.   -1.   -1.    1.    1.  ]
 [ 0.    4.    4.   -7.   -1.  ]
 [ 0.    0.   -6.    1.25 -1.25]
 [ 0.    4.    1.   -4.    1.  ]]
p = 2, i=4
M =
 [[ 1.   -1.   -1.    1.    1.  ]
 [ 0.    4.    4.   -7.   -1.  ]
 [ 0.    0.   -6.    1.25 -1.25]
 [ 0.    0.   -3.    3.    2.  ]]
p = 3, i=4
M =
 [[ 1.    -1.    -1.     1.     1.   ]
 [ 0.     4.     4.    -7.    -1.   ]
 [ 0.     0.    -6.     1.25  -1.25 ]
 [ 0.     0.

In [7]:
detA = 1
for p in range(m):
    detA *= M[p,p]

print('|A| =', detA)


|A| = -57.0


In [8]:
rankA = np.linalg.matrix_rank(A)
print('rank(A) = ', rankA)

rank(A) =  4


In [9]:
(m,n) = np.shape(A)
print('Is full rank= ', rankA == m)

Is full rank=  True


In [10]:
m=2
A1 = A[1:1+m,1:1+m]
print('A = \n', A
detA1 = np.linalg.det(A1) 
1)
print('|A| = detA1A
rankA1 = np.linalg.matrix_rank(A1)1))
print('rank(A) =rankA1(
eigenVal, eigenVec = np.linalg.eig(A1)Aprint('eigenVal = ', eigenVal )
print('eigenVec = ', eigenVec )
A1))


SyntaxError: invalid syntax (Temp/ipykernel_11900/892402566.py, line 4)