In [72]:
import numpy as np

A = np.array(
    [
        [-1, 2, 4, 7, 8],
        [1, 0, 5, -2, 8],
        [0, 2, -4, 7, 8],
        [2, 0, 3, 7, 8],
        [3, 3, 4, 0, 8],
    ]
)

b = np.array(
    [
        [1],
        [2],
        [3],
        [4],
        [5],
    ]
)


In [73]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
a1 = np.trunc(a)
a2 = abs(a - a1)
a2 > 1

abs(a) % 1


array([0.7, 0.5, 0.2, 0.2, 0.5, 0.7, 0. ])

In [74]:
a = np.array([0.0, 0.0, 0.0])
a == 0


array([ True,  True,  True])

In [75]:
import numpy as np

for i in range(20):

    A = np.random.randint(-9, 9, (5, 5))

    if np.linalg.det(A) == 0:
        continue

    b = np.random.randint(-12, 12, (5, 1))

    # M = np.concatenate((A, b), axis=1)

    # print()
    # print("M = \n", M)

    x = np.linalg.solve(A, b)

    x2 = abs(x) % 1
    if (x2 == 0).all() == False:
        continue

    # print("run ", i+1)

    # print("A = \n", A)
    # print()
    # print("b = \n", b)

    # print()
    # print("x = \n", x)

    # get 3x3
    E = A[:3, :3]

    # eigen
    ei_val, ei_vec = np.linalg.eig(E)

    if np.iscomplex(ei_val).any() or np.iscomplex(ei_vec).any():
        continue

    else:
        a = ei_val
        # a1 = np.trunc(a)
        # a2 = abs(a-a1)
        a2 = abs(a) % 1

        if (a2 == 0).all() == False:
            continue

        print("run ", i + 1)

        print("A = \n", A)
        print()
        print("b = \n", b)

        print()
        print("x = \n", x)

        print()
        print("E = \n", E)

        print()
        print("eigen-values = \n", ei_val)

        print()
        print("eigen-vectors = \n", ei_vec)

        print("/////////////////////////////////////////////////////")
        # break


In [76]:
print(x)
x2 = abs(x) % 1
print(x2)
x2 == 0


[[-0.5052177 ]
 [ 1.28463476]
 [ 2.71104714]
 [-0.42821159]
 [-2.95897805]]
[[0.5052177 ]
 [0.28463476]
 [0.71104714]
 [0.42821159]
 [0.95897805]]


array([[False],
       [False],
       [False],
       [False],
       [False]])

In [77]:
c = np.array(
    [1, 2 + 2j],
)
if np.iscomplex(c).any() == True:
    print("complex")

c.dtype
np.iscomplex(c)


complex


array([False,  True])

In [78]:
np.iscomplex(c).any()


True

In [79]:
print()
print("eigen-values = \n", ei_val)

print()
print("eigen-vectors = \n", ei_vec)

for i in range(len(ei_val)):
    print()
    print("eigen-value = ", ei_val[i])
    print()
    print("eigen-vector = \n", ei_vec[:, i])


NameError: name 'ei_val' is not defined

In [ ]:
from sympy import *

AA = Matrix(
    (
        (-1, 2, 4, 7, 8),
        (1, 0, 5, -2, 8),
        (0, 2, -4, 7, 8),
        (2, 0, 3, 7, 8),
        (3, 3, 4, 0, 8),
    )
)

bb = Matrix(
    (
        (1),
        (2),
        (3),
        (4),
        (5),
    )
)

MM = AA.col_insert(5, bb)

v, w, x, y, z = symbols("v,w,x,y,z")

system = MAb[:, :-1], MAb[:, -1]

linsolve(system, v, w, x, y, z)


In [ ]:
MM.rref()


In [ ]:
EE = MAb[:3, :3]

EE


In [ ]:
EE.eigenvals()


In [ ]:
EE.eigenvects()


In [ ]:
EE[0, 0] = -1.0


In [ ]:
EE


In [ ]:
EE.eigenvals()


In [ ]:
EE.eigenvects()


In [21]:
import numpy as np

A = np.array(
    [
        [0, 1, -9, 7, 0],
        [2, 1, -2, -4, -7],
        [0, 0, -9, -5, -1],
        [(3 - 4), 1, 1, -1, 7],
        [1, -6, 5, -9, 7],
    ]
)
print('A: \n', A)


b = np.array(
    [
        [-6],
        [7],
        [5],
        [-2],
        [4],
    ]
)
print('b: ', b)

x = np.array(
    [
        ['a'],
        ['b'],
        ['c'],
        ['d'],
        ['e'],
    ]
)
print('x=\n',x)

Ax = np.append(A, x, axis=1)
Axb = np.append(Ax, b, axis=1)

print('a. A.x=b \n', Axb)

print('b. order of A:', A.shape)
print('c. order of b:', b.shape)

x[:] = '|'
Ax = np.append(A, x, axis=1)
Axb = np.append(Ax, b, axis=1)

print('d. Ab: \n', Axb)

Ab = np.append(A, b, axis=1)
print('e. order of Ab: ', Ab.shape)

Ab = np.append(A.astype(float), b.astype(float), axis=1)
# Ab = np.append(A, b, axis=1)

M, N = Ab.shape
P = M-1
k = 0
i = 0
j = 0
p = 0
print('Ab=\n', Ab)

for p in range(P):
    if(Ab[p, p] == 0):
        for j in range(p+1, M):
            if Ab[j, p] != 0:
                temp = Ab[j].copy()
                Ab[j] = Ab[p]
                Ab[p] = temp
                k += 1
                print('p=', p+1, 'k=', k)
                print('Ab=\n', Ab)
                break

    for i in range(p+1, M):
        Ab[i] = Ab[i] - (Ab[p]*Ab[i, p]/Ab[p, p])

        print('p=', p+1, 'i=', i+1)
        print('Ab=\n', Ab)

print('Ab=\n', Ab)

# backward substitution
x = np.zeros_like(b).astype(float)
for i in range(M-1, 0, -1):
    x[i] = Ab[i, M]
    for j in range(i+1, M):
        x[i] -= Ab[i, j]*x[j]

    x[i] /= Ab[i, i]

print('g. x=\n', x)

# determinant
D = -1**k
for p in range(M):
    D *= Ab[p,p]

print('g. Determinant= ', D)

# rank
r=0
for p in range(M):
    if Ab[p,p] != 0:
        r+=1

print('h. rank= ', r)
print('i. A is full rank= ', r == M)


# eigen matrix
E = A[:3,:3]
print('E=\n', E)

Ev = np.linalg.eig(E)

print(Ev[0])

for i in range(len(Ev[0])):
    print('eigen value: ', Ev[0][i])
    print('eigen vector: \n', (Ev[1][:,i].reshape(3,1)))
    y = (Ev[1][:,i]/Ev[1][0,i])
    print('eigen vector: \n', y.reshape(3,1))
    
Ev

A: 
 [[ 0  1 -9  7  0]
 [ 2  1 -2 -4 -7]
 [ 0  0 -9 -5 -1]
 [-1  1  1 -1  7]
 [ 1 -6  5 -9  7]]
b:  [[-6]
 [ 7]
 [ 5]
 [-2]
 [ 4]]
x=
 [['a']
 ['b']
 ['c']
 ['d']
 ['e']]
a. A.x=b 
 [['0' '1' '-9' '7' '0' 'a' '-6']
 ['2' '1' '-2' '-4' '-7' 'b' '7']
 ['0' '0' '-9' '-5' '-1' 'c' '5']
 ['-1' '1' '1' '-1' '7' 'd' '-2']
 ['1' '-6' '5' '-9' '7' 'e' '4']]
b. order of A: (5, 5)
c. order of b: (5, 1)
d. Ab: 
 [['0' '1' '-9' '7' '0' '|' '-6']
 ['2' '1' '-2' '-4' '-7' '|' '7']
 ['0' '0' '-9' '-5' '-1' '|' '5']
 ['-1' '1' '1' '-1' '7' '|' '-2']
 ['1' '-6' '5' '-9' '7' '|' '4']]
e. order of Ab:  (5, 6)
Ab=
 [[ 0.  1. -9.  7.  0. -6.]
 [ 2.  1. -2. -4. -7.  7.]
 [ 0.  0. -9. -5. -1.  5.]
 [-1.  1.  1. -1.  7. -2.]
 [ 1. -6.  5. -9.  7.  4.]]
p= 1 k= 1
Ab=
 [[ 2.  1. -2. -4. -7.  7.]
 [ 0.  1. -9.  7.  0. -6.]
 [ 0.  0. -9. -5. -1.  5.]
 [-1.  1.  1. -1.  7. -2.]
 [ 1. -6.  5. -9.  7.  4.]]
p= 1 i= 2
Ab=
 [[ 2.  1. -2. -4. -7.  7.]
 [ 0.  1. -9.  7.  0. -6.]
 [ 0.  0. -9. -5. -1.  5.]
 [-1.  1.  1. -

(array([-1.,  2., -9.]),
 array([[-7.07106781e-01, -4.47213595e-01,  7.07106781e-01],
        [ 7.07106781e-01, -8.94427191e-01,  1.58187870e-17],
        [ 0.00000000e+00,  0.00000000e+00,  7.07106781e-01]]))

In [6]:
np.linalg.solve(A, b)


array([[ 0.11219512],
       [ 0.19512195],
       [-0.0097561 ],
       [-0.89756098],
       [-0.42439024]])

In [7]:
np.linalg.det(A)


-8610.0