In [1]:
import numpy as np


def quick_check(A, b, X):
    print(A, "\n.", "\n", X, "\n=", "\n", b)

    D0 = np.linalg.det(A)
    print("\nD0= ", D0)

    x = np.linalg.solve(A, b)
    print("x= \n", x)

    invA = np.linalg.inv(A)
    print("invA= \n", invA)

In [2]:
import numpy as np

dp = 2

A = np.array(
    [
        [-2, -7, -6, 0, 3],
        [-9, -3, 8, 0, 5],
        [-7, 2, 1, -8, 7],
        [1, 4, 1, -3, 7],
        [0, -2, -2, -6, -9],
    ]
)
print("A= \n", A)

X = np.array(
    [
        ["a"],
        ["b"],
        ["c"],
        ["d"],
        ["e"],
    ]
)
print("x= \n", X)

b = np.array(
    [
        [7],
        [-9],
        [-7],
        [2],
        [-5],
    ]
)
print("b= \n", b)

A= 
 [[-2 -7 -6  0  3]
 [-9 -3  8  0  5]
 [-7  2  1 -8  7]
 [ 1  4  1 -3  7]
 [ 0 -2 -2 -6 -9]]
x= 
 [['a']
 ['b']
 ['c']
 ['d']
 ['e']]
b= 
 [[ 7]
 [-9]
 [-7]
 [ 2]
 [-5]]


In [3]:
print("Write the matrices form. A∙x=b\n")
print(A, "\n.", "\n", X, "\n=", "\n", b)
print("A.x = b")

Write the matrices form. A∙x=b

[[-2 -7 -6  0  3]
 [-9 -3  8  0  5]
 [-7  2  1 -8  7]
 [ 1  4  1 -3  7]
 [ 0 -2 -2 -6 -9]] 
. 
 [['a']
 ['b']
 ['c']
 ['d']
 ['e']] 
= 
 [[ 7]
 [-9]
 [-7]
 [ 2]
 [-5]]
A.x = b


In [4]:
print("What is the order of matrix A")

(m, n) = A.shape

print(f"{m} x {n}")

What is the order of matrix A
5 x 5


In [5]:
print("What is the order of matrix b")

(m, n) = b.shape

print(f"{m} x {n}")

What is the order of matrix b
5 x 1


In [6]:
print("Write the augment matrix A_b,	A_b=[A|b]")

Ab = np.hstack((A, b))

Ab = np.round(Ab, dp)

print("Ab =\n", Ab)

Write the augment matrix A_b,	A_b=[A|b]
Ab =
 [[-2 -7 -6  0  3  7]
 [-9 -3  8  0  5 -9]
 [-7  2  1 -8  7 -7]
 [ 1  4  1 -3  7  2]
 [ 0 -2 -2 -6 -9 -5]]


In [7]:
print("What is the order of matrix Ab")

(m, n) = Ab.shape

print(f"{m} x {n}")

What is the order of matrix Ab
5 x 6


In [8]:
print("Solve the system of linear equation using Gaussian Elimination")

Solve the system of linear equation using Gaussian Elimination


In [9]:
P = m
k = 0
i = 0
j = 0
p = 0

wAb = Ab.astype(float).copy()

print("Ab=\n", wAb)

for p in range(P):
    _p = p + 1
    if wAb[p, p] == 0:
        print(f"\na{_p}{_p} = 0")
        for j in range(_p, m):
            _j = j + 1
            if wAb[j, p] != 0:
                print(
                    f"a{_j}{_p} = {wAb[j,p]}. (it is not equal to zero, swap R{_p} and R{_j})"
                )
                temp = wAb[j].copy()
                wAb[j] = wAb[p]
                wAb[p] = temp
                k += 1
                print("p=", _p, "k=", k)
                print("Ab=\n", wAb)
                break

    for i in range(_p, m):
        _i = i + 1
        print()
        print(f"p={_p}, i={_i}, k={k}")
        print(f"R{_i} = R{_i} - R{_p}*(a{_i}{_p}/a{_p}{_p})")
        print(f"R{_i} = {wAb[i]} - {wAb[p]} * ({wAb[i, p]}/{wAb[p, p]})")

        wAb[i] = wAb[i] - (wAb[p] * wAb[i, p] / wAb[p, p])

        print(f"R{_i} = {wAb[i]}")

        wAb = np.round(wAb, dp)
        print("Ab=\n", wAb)

print("Ab=\n", wAb)

Ab=
 [[-2. -7. -6.  0.  3.  7.]
 [-9. -3.  8.  0.  5. -9.]
 [-7.  2.  1. -8.  7. -7.]
 [ 1.  4.  1. -3.  7.  2.]
 [ 0. -2. -2. -6. -9. -5.]]

p=1, i=2, k=0
R2 = R2 - R1*(a21/a11)
R2 = [-9. -3.  8.  0.  5. -9.] - [-2. -7. -6.  0.  3.  7.] * (-9.0/-2.0)
R2 = [  0.   28.5  35.    0.   -8.5 -40.5]
Ab=
 [[ -2.   -7.   -6.    0.    3.    7. ]
 [  0.   28.5  35.    0.   -8.5 -40.5]
 [ -7.    2.    1.   -8.    7.   -7. ]
 [  1.    4.    1.   -3.    7.    2. ]
 [  0.   -2.   -2.   -6.   -9.   -5. ]]

p=1, i=3, k=0
R3 = R3 - R1*(a31/a11)
R3 = [-7.  2.  1. -8.  7. -7.] - [-2. -7. -6.  0.  3.  7.] * (-7.0/-2.0)
R3 = [  0.   26.5  22.   -8.   -3.5 -31.5]
Ab=
 [[ -2.   -7.   -6.    0.    3.    7. ]
 [  0.   28.5  35.    0.   -8.5 -40.5]
 [  0.   26.5  22.   -8.   -3.5 -31.5]
 [  1.    4.    1.   -3.    7.    2. ]
 [  0.   -2.   -2.   -6.   -9.   -5. ]]

p=1, i=4, k=0
R4 = R4 - R1*(a41/a11)
R4 = [ 1.  4.  1. -3.  7.  2.] - [-2. -7. -6.  0.  3.  7.] * (1.0/-2.0)
R4 = [ 0.   0.5 -2.  -3.   8.5  5.5]
Ab

In [10]:
# backward substitution
T = wAb.copy()

m, n = T.shape
x = np.zeros_like(b).astype(float)

for i in range(m - 1, -1, -1):
    _i = i + 1
    print(f"\ni= {_i}, m={m}")
    x[i] = T[i, m]
    print(f"x{_i} = {x[i,0]}")

    for j in range(_i, m):
        _j = j + 1
        print(f"x{_i} = x{_i} - (T{_i}{_j} * x{_j})")
        print(f"x{_i} = {x[i,0]} - ({T[i,j]} * {x[j,0]})")

        x[i] -= T[i, j] * x[j]
        print(f"x{_i} = {x[i,0]}")

    print(f"x{_i} = x{_i} / T{_i}{_i}")
    print(f"x{_i} = {x[i,0]} / {T[i,i]}")
    x[i] /= T[i, i]
    print(f"x{_i} = {x[i,0]}")

    x[i] = np.round(x[i], dp)
    print(f"x{_i} = {x[i,0]}")

print("\nx=\n", x)


i= 5, m=5
x5 = -36.71
x5 = x5 / T55
x5 = -36.71 / -56.47
x5 = 0.6500796883300868
x5 = 0.65

i= 4, m=5
x4 = 4.68
x4 = x4 - (T45 * x5)
x4 = 4.68 - (7.56 * 0.65)
x4 = -0.23399999999999999
x4 = x4 / T44
x4 = -0.23399999999999999 / -1.02
x4 = 0.22941176470588234
x4 = 0.23

i= 3, m=5
x3 = 6.16
x3 = x3 - (T34 * x4)
x3 = 6.16 - (-8.0 * 0.23)
x3 = 8.0
x3 = x3 - (T35 * x5)
x3 = 8.0 - (4.4 * 0.65)
x3 = 5.14
x3 = x3 / T33
x3 = 5.14 / -10.54
x3 = -0.4876660341555977
x3 = -0.49

i= 2, m=5
x2 = -40.5
x2 = x2 - (T23 * x3)
x2 = -40.5 - (35.0 * -0.49)
x2 = -23.35
x2 = x2 - (T24 * x4)
x2 = -23.35 - (0.0 * 0.23)
x2 = -23.35
x2 = x2 - (T25 * x5)
x2 = -23.35 - (-8.5 * 0.65)
x2 = -17.825000000000003
x2 = x2 / T22
x2 = -17.825000000000003 / 28.5
x2 = -0.6254385964912281
x2 = -0.63

i= 1, m=5
x1 = 7.0
x1 = x1 - (T12 * x2)
x1 = 7.0 - (-7.0 * -0.63)
x1 = 2.59
x1 = x1 - (T13 * x3)
x1 = 2.59 - (-6.0 * -0.49)
x1 = -0.3500000000000001
x1 = x1 - (T14 * x4)
x1 = -0.3500000000000001 - (0.0 * 0.23)
x1 = -0.350000000000

In [11]:
# determinant
D = -(1**k)
for p in range(m):
    D *= Ab[p, p]

print("g. Determinant= ", D)

# rank
r = 0
for p in range(m):
    if Ab[p, p] != 0:
        r += 1

print("h. rank= ", r)
print("i. A is full rank= ", r == m)

g. Determinant=  -162
h. rank=  5
i. A is full rank=  True


In [12]:
print(
    "5a. Extract matrix C (3×3) from the coefficient A, in question 4 starting with element a_11 to a_33"
)

m = n = 3
C = A[0:m, 0:n]
print("C= \n", C)

5a. Extract matrix C (3×3) from the coefficient A, in question 4 starting with element a_11 to a_33
C= 
 [[-2 -7 -6]
 [-9 -3  8]
 [-7  2  1]]


In [13]:
print("Find the determinant of matrix C	")

olist = []
alist = []

for i in range(m):
    _i = i + 1
    o = C[0, i]
    olist.append(o)
    a = C.copy()
    a = np.delete(a, 0, 0)
    a = np.delete(a, i, 1)
    alist.append(a.copy())

print("Sub-matrice ")
detC = 0
for i in range(m):
    _i = i + 1
    o = olist[i]
    s = alist[i]
    d1 = ((-1) ** i) * o
    d2 = s[0, 0] * s[1, 1] - s[0, 1] * s[1, 0]
    d = d1 * d2
    print()
    print(f"c1{_i} = {o}")
    print(f"C{_i} = \n{s}")
    print(f"d{_i} = {d1} * {d2} = {d}")

    detC += d
print("\nD = ", detC)

Find the determinant of matrix C	
Sub-matrice 

c11 = -2
C1 = 
[[-3  8]
 [ 2  1]]
d1 = -2 * -19 = 38

c12 = -7
C2 = 
[[-9  8]
 [-7  1]]
d2 = 7 * 47 = 329

c13 = -6
C3 = 
[[-9 -3]
 [-7  2]]
d3 = -6 * -39 = 234

D =  601


In [14]:
print("What is the Rank of C")
r = 0
if detC > 0 or detC < 0:
    m, n = C.shape
    r = m

print("rank= ", r)

What is the Rank of C
rank=  3


In [15]:
print("Find the inverse of matrix C")

m, n = C.shape

print("C= \n", C)


if m != n:
    exit

print("Find co-factor of C")

olist = []
slist = []

Cf = np.zeros_like(C)

isign = 0

for i in range(m):
    _i = i + 1
    for j in range(n):
        _j = j + 1
        o = C[i, j]
        olist.append(o)
        s = C.copy()
        s = np.delete(s, i, 0)
        s = np.delete(s, j, 1)
        slist.append(s.copy())

        #
        d1 = (-1) ** isign
        d2 = s[0, 0] * s[1, 1] - s[0, 1] * s[1, 0]
        d = d1 * d2
        print()
        print(f"c{_i}{_j} = {o}")
        print(f"C{_i}{_j} = \n{s}")
        print(f"d{_i}{_j} = {d1} * {d2} = {d}")

        Cf[i, j] = d

        isign = isign + 1

print("Co-factor= \n", Cf)

Adj = Cf.T
print("Adj= \n", Adj)

print("\ndet C = ", detC)

invA = Adj / detC
print("invA = \n", invA)

# check
print("=check==========================")
np.linalg.inv(C)

Find the inverse of matrix C
C= 
 [[-2 -7 -6]
 [-9 -3  8]
 [-7  2  1]]
Find co-factor of C

c11 = -2
C11 = 
[[-3  8]
 [ 2  1]]
d11 = 1 * -19 = -19

c12 = -7
C12 = 
[[-9  8]
 [-7  1]]
d12 = -1 * 47 = -47

c13 = -6
C13 = 
[[-9 -3]
 [-7  2]]
d13 = 1 * -39 = -39

c21 = -9
C21 = 
[[-7 -6]
 [ 2  1]]
d21 = -1 * 5 = -5

c22 = -3
C22 = 
[[-2 -6]
 [-7  1]]
d22 = 1 * -44 = -44

c23 = 8
C23 = 
[[-2 -7]
 [-7  2]]
d23 = -1 * -53 = 53

c31 = -7
C31 = 
[[-7 -6]
 [-3  8]]
d31 = 1 * -74 = -74

c32 = 2
C32 = 
[[-2 -6]
 [-9  8]]
d32 = -1 * -70 = 70

c33 = 1
C33 = 
[[-2 -7]
 [-9 -3]]
d33 = 1 * -57 = -57
Co-factor= 
 [[-19 -47 -39]
 [ -5 -44  53]
 [-74  70 -57]]
Adj= 
 [[-19  -5 -74]
 [-47 -44  70]
 [-39  53 -57]]

det C =  601
invA = 
 [[-0.03161398 -0.00831947 -0.12312812]
 [-0.078203   -0.07321131  0.11647255]
 [-0.06489185  0.08818636 -0.09484193]]
=check==========================


array([[-0.03161398, -0.00831947, -0.12312812],
       [-0.078203  , -0.07321131,  0.11647255],
       [-0.06489185,  0.08818636, -0.09484193]])

In [16]:
print(
    "Find the eigen values of sub-matrix E from C and order 2×2 (starting with element c_11 to c_22)."
)

E = C[:2, :2]

print("E = \n", E)

Find the eigen values of sub-matrix E from C and order 2×2 (starting with element c_11 to c_22).
E = 
 [[-2 -7]
 [-9 -3]]


In [17]:
I = np.identity(2)

print("I = \n", I)

I = 
 [[1. 0.]
 [0. 1.]]


In [18]:
print(f"|A - yI| = 0")

print()

print(f"|{E} - y{I}| = 0")

|A - yI| = 0

|[[-2 -7]
 [-9 -3]] - y[[1. 0.]
 [0. 1.]]| = 0


In [19]:
# coeff = [3.2, 2, 1]
# np.roots(coeff)
import numpy.polynomial.polynomial as poly

poly.polyroots([-57, 5, 1])

array([-10.45298686,   5.45298686])

In [20]:
import math

a = 1
b = 5
c = -57

D = b**2 - 4 * a * c
x1 = (-b + math.sqrt(D)) / (2 * a)
x2 = (-b - math.sqrt(D)) / (2 * a)

x1, x2

(5.452986860293433, -10.452986860293432)

In [21]:
quick_check(C, b[:3], X[:3])

TypeError: 'int' object is not subscriptable

In [ ]:
E = A[:2, :2]

# eigen
ei_val, ei_vec = np.linalg.eig(E)

print("E= \n", E)

print("ei_val= \n", ei_val)
print("ei_vec= \n", ei_vec)

In [ ]:
n = 4
An = A[:n, :n]
Dn = np.linalg.det(An)
print("D0= ", Dn)

In [ ]:
from sympy import *

AA = Matrix(
    (
        (-2, -7, -6, 0, 3),
        (-9, -3, 8, 0, 5),
        (-7, 2, 1, -8, 7),
        (1, 4, 1, -3, 7),
        (0, -2, -3, -6, -9),
    )
)
AA

In [ ]:
xx = Matrix(
    (
        ("a"),
        ("b"),
        ("c"),
        ("d"),
        ("e"),
    )
)
xx

In [ ]:
bb = Matrix(
    (
        (7),
        (-9),
        (-7),
        (2),
        (-5),
    )
)
bb

In [ ]:
MM = AA.col_insert(5, bb)

v, w, x, y, z = symbols("v,w,x,y,z")

system = MM[:, :-1], MM[:, -1]

linsolve(system, v, w, x, y, z)

In [ ]:
MM.rref()

In [ ]:
d = AA.det()
print(d)

In [ ]:
EE = MM[:2, :2]

EE

In [ ]:
EE.eigenvals()

In [ ]:
EE.eigenvects()

In [ ]:
from sympy import roots
from sympy.abc import x, a, b, c

roots(1 * x**2 + 5 * x - 57, x)

In [ ]:
import numpy as np

x = np.array(
    [
        ["a"],
        ["b"],
        ["c"],
        ["d"],
        ["e"],
    ]
)
print("x=\n", x)

Ax = np.append(A, x, axis=1)
Axb = np.append(Ax, b, axis=1)

print("a. A.x=b \n", Axb)

print("b. order of A:", A.shape)
print("c. order of b:", b.shape)

x[:] = "|"
Ax = np.append(A, x, axis=1)
Axb = np.append(Ax, b, axis=1)

print("d. Ab: \n", Axb)

Ab = np.append(A, b, axis=1)
print("e. order of Ab: ", Ab.shape)

Ab = np.append(A.astype(float), b.astype(float), axis=1)
# Ab = np.append(A, b, axis=1)

M, N = Ab.shape
P = M - 1
k = 0
i = 0
j = 0
p = 0
print("Ab=\n", Ab)

for p in range(P):
    if Ab[p, p] == 0:
        for j in range(p + 1, M):
            if Ab[j, p] != 0:
                temp = Ab[j].copy()
                Ab[j] = Ab[p]
                Ab[p] = temp
                k += 1
                print("p=", p + 1, "k=", k)
                print("Ab=\n", Ab)
                break

    for i in range(p + 1, M):
        Ab[i] = Ab[i] - (Ab[p] * Ab[i, p] / Ab[p, p])

        print("p=", p + 1, "i=", i + 1)
        print("Ab=\n", Ab)

print("Ab=\n", Ab)

# backward substitution
x = np.zeros_like(b).astype(float)
for i in range(M - 1, 0, -1):
    x[i] = Ab[i, M]
    for j in range(i + 1, M):
        x[i] -= Ab[i, j] * x[j]

    x[i] /= Ab[i, i]

print("g. x=\n", x)

# determinant
D = -(1**k)
for p in range(M):
    D *= Ab[p, p]

print("g. Determinant= ", D)

# rank
r = 0
for p in range(M):
    if Ab[p, p] != 0:
        r += 1

print("h. rank= ", r)
print("i. A is full rank= ", r == M)


# eigen matrix
Ne = 2
E = A[:Ne, :Ne]
print("E=\n", E)

Ev = np.linalg.eig(E)

print(Ev[0])

for i in range(len(Ev[0])):
    print("eigen value: ", Ev[0][i])
    print("eigen vector: \n", (Ev[1][:, i].reshape(Ne, 1)))
    y = Ev[1][:, i] / Ev[1][0, i]
    print("eigen vector: \n", y.reshape(Ne, 1))

Ev

In [ ]:
np.linalg.solve(A, b)

In [ ]:
np.linalg.det(A)