In [1]:
import numpy as np

A = np.array([
    [-1, 2, 4, 7, 8],
    [1, 0, 5, -2, 8],
    [0, 2, -4, 7, 8],
    [2, 0, 3, 7, 8],
    [3, 3, 4, 0, 8],
])

b = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
])

M = np.concatenate((A, b), axis=1)
M


array([[-1,  2,  4,  7,  8,  1],
       [ 1,  0,  5, -2,  8,  2],
       [ 0,  2, -4,  7,  8,  3],
       [ 2,  0,  3,  7,  8,  4],
       [ 3,  3,  4,  0,  8,  5]])

In [2]:
np.linalg.solve(A, b)


array([[ 1.08650519],
       [ 0.18685121],
       [-0.11418685],
       [ 0.07612457],
       [ 0.20458478]])

In [3]:
E = A[:3, : 3]
E


array([[-1,  2,  4],
       [ 1,  0,  5],
       [ 0,  2, -4]])

In [4]:
np.linalg.eig(E)


(array([ 2.47531178, -1.87584381, -5.59946797]),
 array([[-0.66462793,  0.97892329, -0.37744996],
        [-0.71389788, -0.14869129, -0.57836903],
        [-0.22049838, -0.14000033,  0.72320176]]))

In [5]:
from sympy import *

AA = Matrix((
    (-1, 2, 4, 7, 8),
    (1, 0, 5, -2, 8),
    (0, 2, -4, 7, 8),
    (2, 0, 3, 7, 8),
    (3, 3, 4, 0, 8),
))

bb = Matrix((
    (1),
    (2),
    (3),
    (4),
    (5),
))

MM = AA.col_insert(5, bb)

v, w, x, y, z = symbols('v,w,x,y,z')

system = MM[:, :-1], MM[:, -1]

linsolve(system, v, w, x, y, z)


{(314/289, 54/289, -33/289, 22/289, 473/2312)}

In [6]:
MM.rref()


(Matrix([
 [1, 0, 0, 0, 0,  314/289],
 [0, 1, 0, 0, 0,   54/289],
 [0, 0, 1, 0, 0,  -33/289],
 [0, 0, 0, 1, 0,   22/289],
 [0, 0, 0, 0, 1, 473/2312]]),
 (0, 1, 2, 3, 4))

In [7]:
EE = MM[:3,:3]

EE

Matrix([
[-1, 2,  4],
[ 1, 0,  5],
[ 0, 2, -4]])

In [8]:
EE.eigenvals()

{-5/3 + 49/(9*(46/27 + sqrt(12837)*I/9)**(1/3)) + (46/27 + sqrt(12837)*I/9)**(1/3): 1,
 -5/3 + 49/(9*(-1/2 + sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3): 1,
 -5/3 + (-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3) + 49/(9*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3)): 1}

In [9]:
EE.eigenvects()

[(-5/3 + (-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3) + 49/(9*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3)),
  1,
  [Matrix([
   [-25/3 + 2*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3) + (-5/3 + (-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3) + 49/(9*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3)))**2/2 + 98/(9*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3))],
   [                                                                                                                                      7/6 + (-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3)/2 + 49/(18*(-1/2 - sqrt(3)*I/2)*(46/27 + sqrt(12837)*I/9)**(1/3))],
   [                                                                                                                                                                                                                                                                  1]])]),
 (-5/3 + 49/(9*(-1/2 + sqrt(3)*I/2)*(46/27 + sqrt(1283

In [10]:
EE[0,0] = -1.0

In [11]:
EE

Matrix([
[-1.0, 2,  4],
[   1, 0,  5],
[   0, 2, -4]])

In [12]:
EE.eigenvals()

{2.47531178171022: 1, -1.87584380763636: 1, -5.59946797407387: 1}

In [13]:
EE.eigenvects()

[(2.47531178171022,
  1,
  [Matrix([
   [0.664627929548358],
   [0.713897877741399],
   [0.220498379632571]])]),
 (-1.87584380763636,
  1,
  [Matrix([
   [   -1.14089630343],
   [0.173293802154503],
   [0.163164839551344]])]),
 (-5.59946797407387,
  1,
  [Matrix([
   [ 0.443533856823003],
   [ 0.679629818130322],
   [-0.849819851533877]])])]