# Matrices

Olagoke Oladokun  
Covenant University, Ota, Nigeria

©2021


In [ ]:
!pip install - q numpy
!pip install - q scipy
!pip install - q sympy


Error: System.OperationCanceledException: Command :SubmitCode: !pip install - q numpy
!pip install - q scipy
!pip ... cancelled.

# GEC220

# Engineering Mathematics II

Matrices and Determinants: Solution of system of linear equations by determinants. Linear dependence and independence, rank of a matrix. General system of linear equations, existence and properties of solution, Gaussian elimination. Matrix inverse by elementary matrices, adjoint, and partitioning methods. Characteristic polynomial, characteristic equation, eigenvalues and eigenvectors.


GEC220
Engineering Mathematics II
3 Units
LH 45
Lecturers
Prof. Vincent
Dr. Adeeyo
Dr. Olagoke

Partial Differentiation: Functions of several variables, continuity and partial derivatives. Total differentials, approximate calculations using differentials. Chain rule. Implicit differentiation. Series representation of functions (Maclaurin & Taylor’s), Taylor’s Theorem. Extremum problems, (analytic method) without and with constraints, Lagrange multipliers, global extremum. Ordinary Differential Equations: Definition, degree, order, linear, non-linear, solution. First order equations, separable variables, equations reducible to separable form, exact equations, integrating factors, homogenous differential equations. Modeling of engineering systems leading to first order differential equations- electric circuit, mixing/dilution, radioactive decay, bacterial culture. 2nd order differential equations with constant coefficients, homogeneous, non-homogeneous, complementary functions, particular integrals, D-operator method. General linear second-order differential equations (without using matrices). Power series solution, Legendre’s differential equation. Modeling of engineering systems leading to 2nd order differential equations- electric circuit, mechanical oscillations-free and forced, resonance. Pre-requisites: MAT 121 and MAT 122.
Matrices and Determinants: Solution of system of linear equations by determinants. Linear dependence and independence, rank of a matrix. General system of linear equations, existence and properties of solution, Gaussian elimination. Matrix inverse by elementary matrices, adjoint, and partitioning methods. Characteristic polynomial, characteristic equation, eigenvalues and eigenvectors.


Contents
1 Matrices 6
1.1 Matrix notation 7
1.2 Addition and Subtraction of Matrices 7
1.3 Multiplication of Matrices 8
1.3.1 Scalar Multiplication 8
1.3.2 Two matrices multiplication 8
1.4 Transpose of matrix 10
1.5 Square matrix 10
1.5.1 Symmetry matrix 10
1.6 Triangular matrix 11
1.7 Diagonal matrix 11
1.8 Unit matrix 11
1.9 Null matrix 12
2 Determinants 13
2.1 Determinants of the second order 13
2.2 Determinants of the third order 14
3 Solution of system of linear equations by determinants 17
3.1 Determinant Equation Method 18
3.1.1 Secondary Degree 18
3.1.2 Third Degree 19
3.2 Cramers Rule 22
3.2.1 For second degree 22
3.2.2 Third degree 22
4 Linear dependence and independence 25
5 Rank of a matrix 27
6 General system of linear equations, 28
7 Existence and properties of solution 31
7.1 Existence of solution 31
7.2 Other properties of the solution 31
8 Gaussian elimination. 33
8.1 Algorithm of Gaussian Elimination 33
8.2 Determinant from Gaussian Elimination 38
9 Matrix inverse by elementary matrices, adjoint, and partitioning methods. 39
9.1 Inverse of a square matrix 39
9.2 Cofactors 39
9.3 Adjoint 41
10 Eigenvalues and Eigenvectors. 43
10.1 Eigenvalues 43
10.1.1 Example 43
10.2 Eigenvectors 44
10.2.1 Example 44


# Matrices


A matrix is a set of real or complex numbers (or elements) arranged in rows and columns to form a rectangular array.
A matrix can be identified by its order denoted as $m \times n \quad (m \ by \ n)$ matrix.

$$
\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]
$$

What is the order of matrix above?. Matrix has $order \ 3\times 3$. The number of rows of $A$, $m = 3$ and number of column, $n = 3$


In [4]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

print('===============================')
print('matrix A =')
print(A)
print()
print('mxn =', np.shape(A))
print('===============================')


matrix A =
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]

mxn = (3, 3)


Use symbolic code


In [5]:
from sympy import *

A = Matrix([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

A


Matrix([
[3, -3, -4],
[1, -1, -1],
[2, -1,  4]])

In [6]:
print('mxn =', A.shape)


mxn = (3, 3)


Similarly, the matrix $C$ below is of $order \ 4\times2$

$$
\left[
    \begin{matrix}
        \begin{matrix}
            1&2\\
        \end{matrix}\\
        \begin{matrix}
            4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2
$$

$$
C=\left[\begin{matrix}\begin{matrix}1&2\\\end{matrix}\\\begin{matrix}4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2
$$


In [21]:
import numpy as np

C = np.array([
    [1, 2], [4, 3], [-1, -5], [3, 3],
])

print('===============================')
print('matrix C =\n', C)
print()
print('mxn =', np.shape(C))
print('===============================')


matrix C =
 [[ 1  2]
 [ 4  3]
 [-1 -5]
 [ 3  3]]

mxn = (4, 2)


In [8]:
from sympy import *

C = Matrix([
    [1, 2], [4, 3], [-1, -5], [3, 3],
])

C


Matrix([
[ 1,  2],
[ 4,  3],
[-1, -5],
[ 3,  3]])

In [9]:
print('mxn =', C.shape)


mxn = (4, 2)


# Quiz

What is the $order$ of the matrices below:

$$
\left[
    \begin{matrix}
        1 & -2 & -4
    \end{matrix}
\right]
$$

(A) $2 \times 2$  
(B) $1 \times -3$  
(C) $3 \times 1$  
(D) $1 \times 3$


## Matrix notation

$$
A=\left[
    \begin{matrix}
        a_{11}&a_{12}&a_{13}\\
        a_{21}&a_{22}&a_{23}\\
        a_{31}&a_{32}&a_{33}\\
    \end{matrix}
    \right]
$$

Matrix $A$ is of order $3 \times 3$ with elements $a_{ij}$ where $i$ and $j$ represents the index of the row and column it belongs in the matrix.


## Addition and Subtraction of Matrices

Addition and subtraction of two matrices can only be achieved if they are the same order.



$$
A\pm B
$$



Only possible if



$$
\left.A\right|m{==}\left.B\right|m\ 
$$
and 
$$
\left.A\right|n{==}\left.B\right|n
$$


Example



$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]
$$



$$
B=\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]
$$



Then
Check the order of $A (2 \times 2)$ and compare to order $B (2 \times 2)$?
Since they are both equal the addition and subtraction is possible.



$$
\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]+\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]=\left[\begin{matrix}3&-6\\8.1&-6.5\\\end{matrix}\right]
$$



$$
\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]-\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]=\left[\begin{matrix}-1&0\\-0.1&2.5\\\end{matrix}\right]
$$


In [10]:
import numpy as np

A = np.array([[1, -3], [4, -2]])
B = np.array([[2, -3], [4.1, -4.5]])

sum = A + B
dif = A - B

print('============================')

print('sum = \n', sum)
print()
print('diference = \n', dif)

print('============================')


sum = 
 [[ 3.  -6. ]
 [ 8.1 -6.5]]

diference = 
 [[-1.   0. ]
 [-0.1  2.5]]


In [11]:
from sympy import *

A = Matrix([[1, -3], [4, -2]])
B = Matrix([[2, -3], [4.1, -4.5]])

sum = A + B
dif = A - B


In [6]:
sum


Matrix([
[  3,   -6],
[8.1, -6.5]])

In [12]:
dif


Matrix([
[                 -1,   0],
[-0.0999999999999996, 2.5]])

## Multiplication of Matrices

### Scalar Multiplication

$$
4\times A= 4\times\left[
    \begin{matrix}
    1&-3 \\
    4&-2 \\
    \end{matrix}
    \right]
    =
    \left[
        \begin{matrix}
        4&-12\\
        16&-8\\
        \end{matrix}
    \right]
$$


In [14]:
import numpy as np

A = np.array(
    [
        [1, -3],
        [4, -2]
    ])

prod = 4*A

print('============================')
print('A= ')
print(A)
print('4*A =\n', prod)
print('============================')


A= 
[[ 1 -3]
 [ 4 -2]]
4*A =
 [[  4 -12]
 [ 16  -8]]


In [19]:
from sympy import *

A = Matrix(
    [
        [1, -3],
        [4, -2]
    ])

prod = 4*A

print('4*A =')

prod


4*A =


Matrix([
[ 4, -12],
[16,  -8]])

## Two matrices multiplication

To multiply any two matrices the number of columns in the first matrix must be equal to the number of rows of the second matrix. The product matrix will have number of rows of the first matrix and number of columns of the second matrix

$$
A\times B =P
$$

Is possible if and only if

$$
    A|n == B|m \quad \Rightarrow \quad P=A|m\times B|n
$$


# Example



$$
C=\left[\begin{matrix}\begin{matrix}1&2\\\end{matrix}\\\begin{matrix}4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2
$$



$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]=m\times n=2\times2
$$




$$
A \times C 
$$
$$
(2 \times 2)\ \times (4 \times 2) 
$$


$$
2 \times (2 \neq 4) \times 2
$$



$$
(2 \neq 4) ∶ \ A \times C \textrm{ is not possible.}
$$


In [5]:
import numpy as np

C = np.array(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = np.array(
    [
        [1, -3],
        [4, -2]
    ]
)

P = A @ C


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [20]:
from sympy import *

C = Matrix(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = Matrix(
    [
        [1, -3],
        [4, -2]
    ]
)

P = A * C

P


ShapeError: Matrix size mismatch: (2, 2) * (4, 2).

Interchanging

$$
C\times A \\
(4\times2)\ \times(2\times2) \\
4\times(2=2)\times2 \\
$$

$$
(2=4)∶\ C\times A \textrm{ is possible.} \\
C\times A\equiv4\times2
$$


Let’s carryout the multiplication.

$$
C\times A=\left[\begin{matrix}\begin{matrix}c_{11}&c_{12}\\\end{matrix}\\\begin{matrix}c_{21}&c_{22}\\c_{31}&c_{32}\\c_{41}&c_{42}\\\end{matrix}\\\end{matrix}\right]\times\left[\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right]
$$


$$
C\times A=\left[\begin{matrix}\begin{matrix}c_{11}a_{11}+c_{12}a_{21}&c_{11}a_{12}+c_{12}a_{22}\\\end{matrix}\\\begin{matrix}c_{21}a_{11}+c_{22}a_{21}&c_{21}a_{12}+c_{22}a_{22}\\c_{31}a_{11}+c_{32}a_{21}&c_{31}a_{12}+c_{32}a_{22}\\c_{41}a_{11}+c_{42}a_{21}&c_{41}a_{12}+c_{42}a_{22}\\\end{matrix}\\\end{matrix}\right]
$$


$$
C\times A=\left[\begin{matrix}\begin{matrix}1\times1+2\times4\ \ \ \ \ \ &1\times-3+2\times-2\\\end{matrix}\\\begin{matrix}4\times1+3\times4&4\times-3+3\times-2\\-1\times1+-5\times4&-1\times-3+-5\times-2\\3\times1+3\times4&3\times-3+3\times-2\\\end{matrix}\\\end{matrix}\right]=\left[\begin{matrix}\begin{matrix}9&-7\\\end{matrix}\\\begin{matrix}16&-18\\-21&13\\15&-15\\\end{matrix}\\\end{matrix}\right]
$$


In [7]:
import numpy as np

C = np.array(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = np.array(
    [
        [1, -3],
        [4, -2]
    ]
)

P = C @ A

print('=========================')
print('P=\n', P)
print('=========================')


P=
 [[  9  -7]
 [ 16 -18]
 [-21  13]
 [ 15 -15]]


In [21]:
from sympy import *

C = Matrix(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = Matrix(
    [
        [1, -3],
        [4, -2]
    ]
)

P = C * A

print('P=')

P


P=


Matrix([
[  9,  -7],
[ 16, -18],
[-21,  13],
[ 15, -15]])

## Transpose of matrix

Interchanging the rows and columns of a matrix is called transpose.

$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]
$$

$$
A^T=\left[\begin{matrix}1&4\\-3&-2\\\end{matrix}\right]
$$


In [11]:
import numpy as np

C = np.array(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = np.array(
    [
        [1, -3],
        [4, -2]
    ]
)

Atrp = np.transpose(A)

print('=========================')
print('A=\n', A)
print('A^T=\n', Atrp)
print()
print('C=\n', C)
print('C^T=\n', np.transpose(C))
print('=========================')


A=
 [[ 1 -3]
 [ 4 -2]]
A^T=
 [[ 1  4]
 [-3 -2]]

C=
 [[ 1  2]
 [ 4  3]
 [-1 -5]
 [ 3  3]]
C^T=
 [[ 1  4 -1  3]
 [ 2  3 -5  3]]


In [28]:
from sympy import *

C = Matrix(
    [
        [1, 2],
        [4, 3],
        [-1, -5],
        [3, 3],
    ]
)

A = Matrix(
    [
        [1, -3],
        [4, -2]
    ]
)

A_T = transpose(A)
C_T = transpose(C)


In [29]:

print('A=\n')
A


A=



Matrix([
[1, -3],
[4, -2]])

In [30]:

print('A_T=\n')
A_T


A_T=



Matrix([
[ 1,  4],
[-3, -2]])

In [31]:

print('C=\n')
C


C=



Matrix([
[ 1,  2],
[ 4,  3],
[-1, -5],
[ 3,  3]])

In [27]:

print('C_T=\n')
C_T


C_T=



Matrix([
[1, 4, -1, 3],
[2, 3, -5, 3]])

# Exercise

$$
A=\left(\begin{matrix}1&-1&-1\\0&-2&3\\2&1&5\\\end{matrix}\right),\quad B=\left(\begin{matrix}1&1&1\\1&1&1\\\end{matrix}\right)
$$

1. $A \times B$
2. $B \times A$
3. $A \times B^T$
4. $B \times A^T$


In [44]:
import numpy as np

A = np.array(
    [
        [1, -1, -1],
        [0, -2, 3],
        [2, 1, 5],
    ]
)

B = np.array(
    [
        [1, 1, 1],
        [1, 1, 1],
    ]
)

try:
    print('A*B=\n', A * B)
except ValueError:
    print('Error multiplying A*B')


try:
    print('B*A=\n', B @ A)
except ValueError:
    print('Error multiplying B*A')

try:
    print('A*B^T=\n', A @ np.transpose(B))
except ValueError:
    print('Error multiplying A*B^T')

try:
    print('B*A^T=\n', B @ np.transpose(A))
except ValueError:
    print('Error multiplying B*A^T=')


Error multiplying A*B
B*A=
 [[ 3 -2  7]
 [ 3 -2  7]]
A*B^T=
 [[-1 -1]
 [ 1  1]
 [ 8  8]]
B*A^T=
 [[-1  1  8]
 [-1  1  8]]


In [54]:
from sympy import *

A = Matrix(
    [
        [1, -1, -1],
        [0, -2, 3],
        [2, 1, 5],
    ]
)

B = Matrix(
    [
        [1, 1, 1],
        [1, 1, 1],
    ]
)


In [55]:
try:
    print('A*B=\n')
    P = None
    P = A * B
except Exception as ex:
    print('Error multiplying A*B')
    print('error: ', ex.args[0])

P


A*B=

Error multiplying A*B
error:  Matrix size mismatch: (3, 3) * (2, 3).


In [56]:
print('B*A=\n')

try:
    P = None
    P = B * A
except Exception as ex:
    print('error: ', ex.args[0])

P


B*A=



Matrix([
[3, -2, 7],
[3, -2, 7]])

In [57]:
print('A*B^T=\n')

try:
    P = None
    P = A * transpose(B)
except Exception as ex:
    print('error: ', ex.args[0])

P


A*B^T=



Matrix([
[-1, -1],
[ 1,  1],
[ 8,  8]])

In [58]:
print('B*A^T=\n')

try:
    P = None
    P = B * transpose(A)
except Exception as ex:
    print('error: ', ex.args[0])

P


B*A^T=



Matrix([
[-1, 1, 8],
[-1, 1, 8]])

## Square matrix


Square matrix is a matrix of order $m \times m$ or $n \times n$. It contains same number of rows and columns.


$$
A=  \left[
        \begin{matrix}
            a_{11} & a_{12} & \cdots & a_{1n}\\
            a_{21} & a_{22} & \cdots & a_{2n}\\
            \vdots & \vdots & \ddots & \vdots \\
            a_{n1} & a_{n2} & \cdots & a_{nn}\\
        \end{matrix}
    \right]
    =n\times n
    =m\times m
$$


$$
A=\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]=3\times3
$$


In [66]:
import numpy as np

A = np.array(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

Atrp = np.transpose(A)

print('=========================')
print('A=\n', A)
print('\nmxn= ', np.shape(A))
print()
print('A^T=\n', Atrp)
print('\nmxn= ', np.shape(Atrp))
print('=========================')


A=
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

mxn=  (3, 3)

A^T=
 [[ 3  1  2]
 [-3 -1 -1]
 [-4 -2  4]]

mxn=  (3, 3)


In [67]:
from sympy import *

A = Matrix(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

A_T = transpose(A)

print('A=\n')

A


A=



Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

In [71]:
print('mxn= ')
A.shape


mxn= 


(3, 3)

In [73]:
print('A^T=')
A_T


A^T=


Matrix([
[ 3,  1,  2],
[-3, -1, -1],
[-4, -2,  4]])

In [74]:
print('mxn= ')
A_T.shape


mxn= 


(3, 3)

### Symmetry matrix

A square matrix is symmetrical if $a_{ij}=a_{ji}$, meaning $S=S^T$.

$$
S=\left[\begin{matrix}1&2&3\\2&4&5\\3&5&6\\\end{matrix}\right]
$$

$$
S^T=\left[\begin{matrix}1&2&3\\2&4&5\\3&5&6\\\end{matrix}\right]
$$


In [80]:
import numpy as np

S = np.array(
    [
        [1, 2, 3],
        [2, 4, 5],
        [3, 5, 6],
    ]
)

S_T = np.transpose(S)
print('=========================')
print('S=\n', S)
print('\nmxn = ', np.shape(S))
print()
print('S^T=\n', S_T)
print('\nmxn = ', np.shape(S_T))
print()
print('S == S^T')
print(S == S_T)
print('=========================')


S=
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

mxn =  (3, 3)

S^T=
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

mxn =  (3, 3)

S == S^T
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [81]:
A = np.array(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

A_T = np.transpose(A)

print('=========================')

print('A=\n', A)
print('\nmxn = ', np.shape(A))
print()
print('A^T=\n', A_T)
print('\nmxn = ', np.shape(A_T))
print()
print('A == A^T')
print(A == A_T)
print('=========================')


A=
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

mxn =  (3, 3)

A^T=
 [[ 3  1  2]
 [-3 -1 -1]
 [-4 -2  4]]

mxn =  (3, 3)

A == A^T
[[ True False False]
 [False  True False]
 [False False  True]]


In [89]:
from sympy import *

S = Matrix(
    [
        [1, 2, 3],
        [2, 4, 5],
        [3, 5, 6],
    ]
)

S_T = transpose(S)

print('S=')

S


S=


Matrix([
[1, 2, 3],
[2, 4, 5],
[3, 5, 6]])

In [90]:
print('mxn = ', S.shape)


mxn =  (3, 3)


In [91]:
print('S^T=')
S_T


S^T=


Matrix([
[1, 2, 3],
[2, 4, 5],
[3, 5, 6]])

In [99]:
print('mxn =', S_T.shape)


mxn = (3, 3)


In [97]:
print('(S == S^T) =', S == S_T)


(S == S^T) = True


# Example


In [102]:
A = Matrix(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

A_T = transpose(A)

print('A=')
A


A=


Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

In [103]:
print('mxn = ', A.shape)


mxn =  (3, 3)


In [104]:
print('A^T=')
A_T


A^T=


Matrix([
[ 3,  1,  2],
[-3, -1, -1],
[-4, -2,  4]])

In [105]:
print('mxn = ', A_T.shape)


mxn =  (3, 3)


In [106]:
print('(A == A^T) =', A == A_T)


(A == A^T) = False


### Triangular matrix

A triangular matrix is a square matrix with all elements below the leading diagonal equal to zero.

$$
A=\left[\begin{matrix}1&2&3\\0&4&5\\0&0&6\\\end{matrix}\right]
$$


In [107]:
import numpy as np

A = np.array(
    [
        [1, 2, 3],
        [0, 4, 5],
        [0, 0, 6],
    ]
)

print('A=\n', A)


A=
 [[1 2 3]
 [0 4 5]
 [0 0 6]]


In [108]:
from sympy import *

A = Matrix(
    [
        [1, 2, 3],
        [0, 4, 5],
        [0, 0, 6],
    ]
)

print('A=')
A


A=


Matrix([
[1, 2, 3],
[0, 4, 5],
[0, 0, 6]])

### Diagonal matrix

A diagonal matrix is a square matrix with all elements zero except the leading diagonal.

$$
A=\left[\begin{matrix}1&0&0\\0&4&0\\0&0&6\\\end{matrix}\right]
$$


In [109]:
import numpy as np

A = np.array(
    [
        [1, 0, 0],
        [0, 4, 0],
        [0, 0, 6],
    ]
)

print('A=\n', A)


A=
 [[1 0 0]
 [0 4 0]
 [0 0 6]]


In [110]:
from sympy import *

A = Matrix(
    [
        [1, 0, 0],
        [0, 4, 0],
        [0, 0, 6],
    ]
)

print('A=')
A


A=


Matrix([
[1, 0, 0],
[0, 4, 0],
[0, 0, 6]])

### Unit matrix

A Unit matrix is a special diagonal matrix with the leading diagonal element values all unity or ones. The unit matrix is denoted by I.

$$
\mathbb{I}=\left[\begin{matrix}1&0&0\\0&1&0\\0&0&1\\\end{matrix}\right]
$$


In [112]:
import numpy as np

I = np.array(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
    ]
)

print('I=\n', I)


I=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [111]:
from sympy import *

I = Matrix(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
    ]
)

print('I=')
I


I=


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [119]:
import numpy as np

I = np.eye(3, dtype=int)

print('I=\n', I)


I=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Useful property

A useful property

$$
A.I=I.A=A
$$


In [2]:
import numpy as np

A = np.array(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

I = np.identity(3)

print('=========================')
print('A =\n', A)
print()
print('I =\n', I)
print()
print('A * I=\n', A @ I)
print()
print('I * A=\n', I @ A)
print('=========================')


A =
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A * I=
 [[ 3. -3. -4.]
 [ 1. -1. -2.]
 [ 2. -1.  4.]]

I * A=
 [[ 3. -3. -4.]
 [ 1. -1. -2.]
 [ 2. -1.  4.]]


In [125]:
from sympy import *

A = Matrix(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

print('A =')
A


A =


Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

In [126]:
I = Identity(3)
print('I =')
I


I =


I

In [127]:
print('A * I=')
A * I


A * I=


Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

In [128]:
print('I * A=')
I * A


I * A=


Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

## Null matrix

A null matrix is one whose elements are all zero.

$$
N=\left[\begin{matrix}0&0&0\\0&0&0\\0&0&0\\\end{matrix}\right]
$$


In [130]:
import numpy as np

N = np.array(
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ]
)

print('=========================')
print('N =\n', N)
print('=========================')


N =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [131]:
import numpy as np

N = np.zeros((3, 3))

print('=========================')
print('N =\n', N)
print('=========================')


N =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [133]:
from sympy import *

N = zeros(3)

print('N =')
N


N =


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

#### Useful property

A useful property

$$
A.B=0
$$

we cannot say $A=0$ or $B=0$


In [136]:
import numpy as np

A = np.array(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

N = np.zeros((3, 3))

print('=========================')
print('A =\n', A)
print()
print('N =\n', N)
print()
print('A * N=\n', A @ N)
print()
print('N * A=\n', N @ A)
print('=========================')


A =
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

N =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A * N=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

N * A=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
from sympy import *

A = Matrix(
    [
        [3, -3, -4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

N = zeros(3)

print('=========================')
print('A =\n', A)
print()
print('N =\n', N)
print()
print('A * N=\n', A @ N)
print()
print('N * A=\n', N @ A)
print('=========================')


A =
 Matrix([[3, -3, -4], [1, -1, -2], [2, -1, 4]])

N =
 Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

A * N=
 Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

N * A=
 Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])


In [139]:
print('A =')
A


A =


Matrix([
[3, -3, -4],
[1, -1, -2],
[2, -1,  4]])

In [140]:
print('N =')
N


N =


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [141]:
print('A * N=')
A * N


A * N=


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [142]:
print('N * A=')
N * A


N * A=


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

# Determinants


The arrangement of numbers in an equal rows and columns bounded by a straight bar is called determinant.

$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|
$$


## Determinants of the second order

The symbol above is determinant of a $2\times 2$ (two by two matrix) with element $a_{11}$ on row 1 and column 1 and $a_{12}$ is element on row 1 and column 2. It means each element is identified by row and column number subscript $i \textrm{and} j: a_{ij}$.

By definition,

$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|=a_{11}a_{22}-a_{12}a_{21}
$$


To find determinant of

$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|
$$

we must multiply the elements diagonally to form the product terms in the expansion:

$$
\textrm{we multiply }
\left|
    \begin{matrix}
        a_{11} & \\
        & a_{22}\\
    \end{matrix}
\right|

\textrm{ then subtract the product }

\left|
    \begin{matrix}
         & a_{12}\\
        a_{21} & \\
    \end{matrix}
\right|
$$


Note:  
$a_{11}$ before $a_{12}$ i.e column 1 before 2.

$$
\left|
    \begin{matrix}
        1 & -3\\
        4 & -2\\
    \end{matrix}
\right|
=(1)(-2)-(-3)(4)=-2+12=10
$$

Or

$$
\left|
    \begin{matrix}
        1&\\
        &-2\\
    \end{matrix}
\right|
-
\left|
    \begin{matrix}
         & -3\\
        4 & \\
    \end{matrix}
\right|
= 1\times -2 --3\times 4 = 10
$$


In [3]:
import numpy as np

A = np.array(
    [
        [1, -3],
        [4, -2],
    ]
)

print("A = \n", A)

det_A = np.linalg.det(A)

print("|A| = ", det_A)


A = 
 [[ 1 -3]
 [ 4 -2]]
|A| =  10.000000000000002


In [144]:
from sympy import *
x, y = symbols('x y')

A = Matrix(
    [
        [1.0, -3],
        [4, -2]
    ]
)
print("A=")
A


A=


Matrix([
[1.0, -3],
[  4, -2]])

In [148]:
print('|A| =', A.det())


|A| = 10.0000000000000


# More example in class

Generate question from the students/participants


## Determinants of the third order

A determinant of the third order contains 3 rows and 3 columns.

$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|
$$


In order to find the determinant of a higher order the matrix minor must be developed until second order is reached.
Developing each element in the first row minor:

$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|
\left|\begin{matrix}+&-&+\\& &\\&&\\\end{matrix}\right|
$$

For $a_{11}$

$$
\left|\begin{matrix}a_{11}&&\\&a_{22}&a_{23}\\&a_{32}&a_{33}\\\end{matrix}\right|
\begin{matrix}a_{11}\\\\\end{matrix}\left|\begin{matrix}a_{22}&a_{23}\\a_{32}&a_{33}\\\end{matrix}\right|=a_{11}\left(a_{22}a_{33}-a_{23}a_{32}\right)
$$

For $a_{12}$

$$
\left|\begin{matrix}&a_{12}&\\a_{21}&&a_{23}\\a_{31}&&a_{33}\\\end{matrix}\right|
\begin{matrix}{-a}_{12}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{23}\\a_{31}&a_{33}\\\end{matrix}\right|=-a_{12}\left(a_{21}a_{33}-a_{23}a_{31}\right)
$$

For $a_{13}$

$$
\left|\begin{matrix}&&a_{13}\\a_{21}&a_{22}&\\a_{31}&a_{32}&\\\end{matrix}\right|
\begin{matrix}a_{13}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{22}\\a_{31}&a_{32}\\\end{matrix}\right|=a_{13}\left(a_{21}a_{32}-a_{22}a_{31}\right)
$$


Summing all together:

$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|=\begin{matrix}a_{11}\\\\\end{matrix}\left|\begin{matrix}a_{22}&a_{23}\\a_{32}&a_{33}\\\end{matrix}\right|\begin{matrix}{-a}_{12}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{23}\\a_{31}&a_{33}\\\end{matrix}\right|\begin{matrix}{+a}_{13}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{22}\\a_{31}&a_{32}\\\end{matrix}\right|
$$


# Example


$$
\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|
=\begin{matrix}3\\\\\end{matrix}\left|\begin{matrix}-1&-1\\-1&4\\\end{matrix}\right|\begin{matrix}-\\\\\end{matrix}\begin{matrix}-3\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&4\\\end{matrix}\right|\begin{matrix}+\\\\\end{matrix}\begin{matrix}-4\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&-1\\\end{matrix}\right|
$$

$$
=3\left((-1\times4)-(-1\times-1)\right)--3((1\times4)-(-1\times2))+-4((1\times-1)-(-1\times2))
$$

$$
=3\left(-4-1\right)--3(4-(-2))+-4(-1-(-2))
$$

$$
=3\left(-5\right)+3(6)-4(1)
$$

$$
=-15+18-4=-1
$$


Try

$$
\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|
$$

Answer

$$
\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0
$$


In [152]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

detA = np.linalg.det(A)

print("A = \n", A)

print("|A| = ", detA)


A = 
 [[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]
|A| =  -0.9999999999999998


In [157]:
from sympy import *

A = Matrix([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

detA = A.det()

print("A = \n")
A


A = 



Matrix([
[3, -3, -4],
[1, -1, -1],
[2, -1,  4]])

In [158]:
print("|A| = ", detA)


|A| =  -1


In [159]:
from sympy import *

A = Matrix([
    [3.0, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

detA = A.det()

print("A = \n")
A


A = 



Matrix([
[3.0, -3, -4],
[  1, -1, -1],
[  2, -1,  4]])

In [160]:
print("|A| = ", detA)


|A| =  -1.00000000000000


# Solution of system of linear equations by determinants


A system of linear equations of the second degree of two unknowns can be written below:

$$
a_{11}x+a_{12}y=b_1 \\
a_{21}x+a_{22}y=b_2
$$

and can further be written in matrices form as


$$
\left[\begin{matrix}a_{11}&a_{11}\\a_{11}&a_{11}\\\end{matrix}\right]\ \ \left[\begin{matrix}x\\y\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\\end{matrix}\right]\ \
$$


$$
A . x=b
$$

Solving Simultaneous Equation

$$
2x + 3y = 10\\
4x + y = 1
$$

By elimination and substitution


$$
x=-\frac{7}{10},\quad y=\frac{38}{10}
$$

## Determinant Equation Method

### Secondary Degree

$$
2x + 3y = 10\\
4x + y = 1
$$

could be written as:


$$
2x+3y-10=0 \quad \left(a\right) \\
4x+y-1=0 \quad \left(b\right)
$$

and

$$
a_{11}x+a_{12}y+b_1=0 \quad \left(a\right) \\
a_{21}x+a_{22}y+b_2=0 \quad \left(b\right)
$$


The solution

$$
\frac{x}{∆_1}=\frac{-y}{∆_2}=\frac{1}{∆_0}
$$

$$
x=\frac{∆_1}{∆_0}, \quad y=\frac{-∆_2}{∆_0}
$$

where

$$
∆_0=\left|
        \begin{matrix}
            a_{11} & a_{12} \\
            a_{21} & a_{22}
        \end{matrix}
    \right|
,\quad
∆_1=\left|
        \begin{matrix}
            a_{12} & b_{1} \\
            a_{22} & b_{2}
        \end{matrix}
    \right|
,\quad
∆_2=\left|
        \begin{matrix}
            a_{11} & b_{1} \\
            a_{21} & b_{2}
        \end{matrix}
    \right|
$$


Solving Equation

$$
2x+3y-10=0 \quad \left(a\right) \\
4x+y-1=0 \quad \left(b\right)
$$

$$
∆_0=\left|
        \begin{matrix}
            2 & 3 \\
            4 & 1
        \end{matrix}
    \right|
    =
    (2\times 1)-(3\times 4)=2-12=-10
$$

$$
∆_1=\left|
        \begin{matrix}
            3 & -10 \\
            1 & -1
        \end{matrix}
    \right|
    =
    (3\times -1)-(-10 \times 1)=-3--10=7
$$

$$
∆_2=\left|
        \begin{matrix}
            2 & -10 \\
            4 & -1
        \end{matrix}
    \right|
    =
    (2 \times -1)-(-10 \times 4)=-2--40=38
$$

$$
x=\frac{∆_1}{∆_0}=\frac{7}{-10} =\left. -\frac{7}{10} \right. \\
y=\frac{-∆_2}{∆_0}=\left.-\frac{38}{-10}\right.=\frac{38}{10}
$$


### The solution for higher degree system of linear equations are:

### For third degree:

$$
\frac {x}{∆_1}=\frac {-y}{∆_2}= \frac {z}{∆_2}=\frac {-1}{∆_0}
$$

$$
x=\frac {-∆_1}{∆_0}, \quad y=\frac {∆_2}{∆_0}, \quad z=\frac {-∆_3}{∆_0}
$$

Note: The positive and negative signs alternate has the degree increases.


### Third Degree


Solve

$$
3x -3y - 4z = 1 \\
x - y - z = 2 \\
2x-y+ 4z =3
$$

Rearrange

$$
3x -3y -4z -1= 0 \\
x - y - z -2 =0 \\
2x - y + 4z -3 = 0
$$


Extract the matrix of coefficients:

$$
\left[\begin{matrix}\begin{matrix}\begin{matrix}3\\1\\2\\\end{matrix}&\begin{matrix}-3\\-1\\-1\\\end{matrix}\\\end{matrix}&\begin{matrix}\begin{matrix}-4\\-1\\4\\\end{matrix}&\begin{matrix}-1\\-2\\-3\\\end{matrix}\\\end{matrix}\\\end{matrix}\right]
$$


$$
∆_0 =
    \begin{bmatrix}
    3 & -3 & -4 \\
    1 & -1 & -1 \\
    2 & -1 &  4 \\
    \end{bmatrix}
    =-1
$$


$$
∆_1 = \left|\begin{matrix}

-3 & -4 & -1 \\
-1 & -1 & -2 \\
-1 & 4 & -3
\end{matrix} \right|
=
$$



$$
=\begin{matrix}-3\\\\\end{matrix}\left|\begin{matrix}-1&-2\\4&-3\\\end{matrix}\right|\begin{matrix}-\\\\\end{matrix}\begin{matrix}-4\\\\\end{matrix}\left|\begin{matrix}-1&-2\\-1&-3\\\end{matrix}\right|\begin{matrix}+\\\\\end{matrix}\begin{matrix}-1\\\\\end{matrix}\left|\begin{matrix}-1&-1\\-1&4\\\end{matrix}\right|
$$

$$
=-3\left(3--8\right)--4(3-2)+-1(-4-1)
$$

$$
=-3\left(11\right)+4(1)-(-5)=-24
$$


$$
∆_2= \left|
    \begin{matrix}
    3 & -4 & -1 \\
    1 & -1 & -2 \\
    2 & 4 & -3
    \end{matrix}
    \right|
$$

$$
=\begin{matrix}3\\\\\end{matrix}\left|\begin{matrix}-1&-2\\4&-3\\\end{matrix}\right|\begin{matrix}-\\\\\end{matrix}\begin{matrix}-4\\\\\end{matrix}\left|\begin{matrix}1&-2\\2&-3\\\end{matrix}\right|\begin{matrix}+\\\\\end{matrix}\begin{matrix}-1\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&4\\\end{matrix}\right|
$$

$$
=3\left(3--8\right)--4(-3--4)+-1(4--2)
$$

$$
=3\left(11\right)+4(1)-(6)=31
$$


$$
∆_3 = \left|
    \begin{matrix}
    3 & -3 & -1 \\
    1 & -1 & -2 \\
    2 & -1 & -3
    \end{matrix}
    \right|
$$

$$
=\begin{matrix}3\\\\\end{matrix}\left|\begin{matrix}-1&-2\\-1&-3\\\end{matrix}\right|\begin{matrix}-\\\\\end{matrix}\begin{matrix}-3\\\\\end{matrix}\left|\begin{matrix}1&-2\\2&-3\\\end{matrix}\right|\begin{matrix}+\\\\\end{matrix}\begin{matrix}-1\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&-1\\\end{matrix}\right|
$$

$$
=3\left(3-2\right)--3(-3--4)+-1(-1--2)
$$

$$
=3\left(1\right)+3(1)-(1)=5
$$


From Equation 2.13


$$
x= \frac{-∆_1}{∆_0},    y=\frac{∆_2}{∆_0},    z=\frac{-∆_3}{∆_0}
$$

$$
x=-\frac{-24}{-1},\ \ \ \ y=\frac{31}{-1},\ \ \ \ z=-\frac{5}{-1}
$$

$$
x=-24,\ \ \ \ y=-31,\ \ \ \ z=5
$$


In [33]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

b = np.array([1, 2, 3])

M = np.zeros((3,4))

M[:,:3] = A[:]
M[:,3] = -np.transpose(b)

print('M =\n', M)

M0 = M[:,:3]
print('M0 =\n', M0)

M1 = M[:,1:]
print('M1 =\n', M1)

M2 = M[:,[0,2,3]]
print('M2 =\n', M2)

M3 = M[:,[0,1,3]]
print('M3 =\n', M3)

D0 = np.linalg.det(M0)
D1 = np.linalg.det(M1)
D2 = np.linalg.det(M2)
D3 = np.linalg.det(M3)

print('D0 = ', D0)
print('D1 = ', D1)
print('D2 = ', D2)
print('D3 = ', D3)

x = -D1/D0
y = D2/D0
z = -D3/D0

print('x = ',x)
print('y = ',y)
print('z = ',z)


M =
 [[ 3. -3. -4. -1.]
 [ 1. -1. -1. -2.]
 [ 2. -1.  4. -3.]]
M0 =
 [[ 3. -3. -4.]
 [ 1. -1. -1.]
 [ 2. -1.  4.]]
M1 =
 [[-3. -4. -1.]
 [-1. -1. -2.]
 [-1.  4. -3.]]
M2 =
 [[ 3. -4. -1.]
 [ 1. -1. -2.]
 [ 2.  4. -3.]]
M3 =
 [[ 3. -3. -1.]
 [ 1. -1. -2.]
 [ 2. -1. -3.]]
D0 =  -0.9999999999999998
D1 =  -24.000000000000014
D2 =  31.000000000000014
D3 =  5.000000000000001
x =  -24.00000000000002
y =  -31.00000000000002
z =  5.000000000000002


In [6]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

b = np.array([1, 2, 3])

[x,y,z] = np.linalg.solve(A, b)

x,y,z

(-24.00000000000001, -31.00000000000001, 5.000000000000002)

In [9]:
from sympy import * 

M = Matrix([
    [3, -3, -4, 1],
    [1, -1, -1, 2],
    [2, -1, 4, 3]
])

x = linsolve(M)

x

{(-24, -31, 5)}

In [63]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

b = np.array([1, 2, 3])

M = np.zeros((3,4))

M[:,:3] = A[:]
M[:,3] = -np.transpose(b)

print('M =\n', M)

m,n = M.shape

mk=[]
k = []
for i in range(n):
    k = []
    for j in range(n):
        if(i == j):
            continue
        k.append(j)
    mk.append(k)


MD = []
MD.append(M[:,mk[m]])

for i in range(1,n):
    MD.insert(i, M[:,mk[i-1]])
    

D = []
X = []
for i in range(n):
    print('M[',i,'] =\n', MD[i])
    D.append(np.linalg.det(MD[i]))
    print('D[',i,'] =\n', D[i])
    x = ((-1)**i)*(D[i]/D[0])
    X.append(x)
    
print('X=', X[1:])

M =
 [[ 3. -3. -4. -1.]
 [ 1. -1. -1. -2.]
 [ 2. -1.  4. -3.]]
M[ 0 ] =
 [[ 3. -3. -4.]
 [ 1. -1. -1.]
 [ 2. -1.  4.]]
D[ 0 ] =
 -0.9999999999999998
M[ 1 ] =
 [[-3. -4. -1.]
 [-1. -1. -2.]
 [-1.  4. -3.]]
D[ 1 ] =
 -24.000000000000014
M[ 2 ] =
 [[ 3. -4. -1.]
 [ 1. -1. -2.]
 [ 2.  4. -3.]]
D[ 2 ] =
 31.000000000000014
M[ 3 ] =
 [[ 3. -3. -1.]
 [ 1. -1. -2.]
 [ 2. -1. -3.]]
D[ 3 ] =
 5.000000000000001
X= [-24.00000000000002, -31.00000000000002, 5.000000000000002]


## Cramers Rule


### For second degree


For a system of two linear equations in two unknowns (x, y) given below:


$$
a_{11}x + a_{12}y = b_1  \\
a_{21}x + a_{22}y = b_2
$$


Cramer’s rule states that:


$$
x=\frac{\left|\begin{matrix}b_1&a_{12}\\b_2&a_{22}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|},\ \ \ \ y=\frac{\left|\begin{matrix}a_{11}&b_1\\a_{21}&b_2\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|}\
$$


The denominator is the determinant of the coefficients of x and y. The numerator for x is the determinant of coefficient matrix when coefficient of x is replaced by b. Similarly, the numerator for y is the determinant of coefficient matrix when coefficient of y is replaced by b.


### Third degree


$$
a_{11}x+a_{12}y+a_{13}z=b_1 \\
a_{21}x+a_{22}y+a_{23}z=b_2 \\
a_{31}x+a_{32}y+a_{33}z=b_3
$$


$$
x=\frac{\left|\begin{matrix}b_1&a_{12}&a_{13}\\b_2&a_{22}&a_{23}\\b_3&a_{32}&a_{33}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|},
\quad
y=?, \quad z=?
$$


$$
y=\frac{\left|\begin{matrix}a_{11}&b_1&a_{13}\\a_{21}&b_2&a_{23}\\a_{31}&b_3&a_{33}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|}
$$


$$
z=\frac{\left|\begin{matrix}a_{11}&a_{12}&b_1\\a_{21}&a_{22}&b_2\\a_{31}&a_{32}&b_3\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|}
$$


The Cramer’s rule can be generalized:


$$
x=\frac{D_x}{D},
\quad
y=\frac{D_y}{D},
\quad
z=\frac{D_z}{D}
$$


Example 3.3


Solve


$$
3x\ -3y-4z=1 \\
x-y- z=2 \\
2x-y+ 4y=3
$$


$$
x=\frac{\left|\begin{matrix}1&-3&-4\\2&-1&-1\\3&-1&4\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{24}{-1}=-24
$$


$$
y=\frac{\left|\begin{matrix}3&1&-4\\1&2&-1\\2&3&4\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{31}{-1}=-31
$$


$$
z=\frac{\left|\begin{matrix}3&-3&1\\1&-1&2\\2&-1&3\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{-5}{-1}=5
$$


Note: For both the determinant Equation Method and Cramer’s rule determinant, $ ∆_0 or D $ , the coefficient of the unknown must not equal zero.

$$
∆_0≠0 \quad or \quad D≠0
$$


In [70]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4]
])

b = np.array([1, 2, 3])

M = A[:]
print('M0 =\n', M)

M1 = M.copy()
M1[:,0] = np.transpose(b)
print('M1 =\n', M1)

M2 = M.copy()
M2[:,1] = np.transpose(b)
print('M2 =\n', M2)

M3 = M.copy()
M3[:,2] = np.transpose(b)
print('M3 =\n', M3)

D0 = np.linalg.det(M0)
D1 = np.linalg.det(M1)
D2 = np.linalg.det(M2)
D3 = np.linalg.det(M3)

print('D0 = ', D0)
print('D1 = ', D1)
print('D2 = ', D2)
print('D3 = ', D3)

x = D1/D0
y = D2/D0
z = D3/D0

print('x = ',x)
print('y = ',y)
print('z = ',z)


M0 =
 [[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]
M1 =
 [[ 1 -3 -4]
 [ 2 -1 -1]
 [ 3 -1  4]]
M2 =
 [[ 3  1 -4]
 [ 1  2 -1]
 [ 2  3  4]]
M3 =
 [[ 3 -3  1]
 [ 1 -1  2]
 [ 2 -1  3]]
D0 =  -0.9999999999999998
D1 =  24.000000000000014
D2 =  31.0
D3 =  -5.000000000000001
x =  -24.00000000000002
y =  -31.000000000000007
z =  5.000000000000002


# Linear dependence and independence


A matrix is said to be linearly dependent if the determinant is zero and linearly independent if the determinant is not zero.


Linear dependence


$$
D=\left|A\right|=\ 0
$$


And Linear independence


$$
D=\left|A\right|\neq\ 0
$$


Check if the matrices below are linear dependence or independence:


$$
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|
$$

$$
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|
$$


What is your answer?


$$
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0
$$

$$
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1
$$


In [71]:
import numpy as np

A = np.array([
    [2,3,4],
    [6,1,0],
    [2,3,4],
])

np.linalg.det(A)

0.0

In [72]:
import numpy as np

B = np.array([
    [3,-3,-4],
    [1,-1,-1],
    [2,-1,4],
])

np.linalg.det(B)

-0.9999999999999998

# Rank of a matrix


The rank of an $ m x n $ matrix $ A $ is the order of the largest square, linear independence sub-matrix. In order to get a matrix rank you must get a non-zero determinant matrix of the original m x n matrix or a sub-matrix.


Check the rank of matrix $B$ below:


$$
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1


$$


Since the determinant is non-zero the $ rank = 3 $.


In [76]:
import numpy as np

B = np.array([
    [3,-3,-4],
    [1,-1,-1],
    [2,-1,4],
])

print('|B| = ', np.linalg.det(B))

r = np.linalg.matrix_rank(B)
print('rank = ', r)

|B| =  -0.9999999999999998
rank =  3


Similarly, check for matrix $A$.


$$
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0
$$


The determinant is zero, we need to check for the determinant of its sub-matrix:


$$
A_1=\left|\begin{matrix}2&3\\6&1\\\end{matrix}\right|=-16
$$


Since the determinant of the sub-matrix A1 is non-zero, we can conclude that matrix $A$ is of $rank = 2$.


In [77]:
import numpy as np

A = np.array([
    [2,3,4],
    [6,1,0],
    [2,3,4],
])

print('|A| = ', np.linalg.det(A))

r = np.linalg.matrix_rank(A)
print('rank = ', r)

|A| =  0.0
rank =  2


# General system of linear equations


A system linear of equations below with three unknown $x, y, z$:


$$
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1 \\
a_{21}x_1+a_{22}x_2+a_{23}x_3=b_2 \\
a_{31}x_1+a_{32}x_2+a_{33}x_3=b_3
$$


can be represented using matrix notation:


$$
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\b_3\\\end{matrix}\right]
$$


Similarly,


$$
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1 \\
a_{21}x_1+a_{22}x_2+a_{23}x_3=b_2
$$


$$
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\\end{matrix}\right]
$$


Generally,


$$
\begin{matrix}
\begin{matrix}
\begin{matrix}
a_{11}x_1\\a_{21}x_1\\a_{31}x_1\\\end{matrix}&\begin{matrix}a_{12}x_2\\a_{22}x_2\\a_{32}x_2\\\end{matrix}&\begin{matrix}a_{13}x_3\\a_{23}x_3\\a_{33}x_3\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}\begin{matrix}a_{1n}x_n&=&b_1\\\end{matrix}\\\begin{matrix}a_{2n}x_n&=&b_2\\\end{matrix}\\\begin{matrix}a_{3n}x_n&=&b_3\\\end{matrix}\\\end{matrix}\\\begin{matrix}\vdots\ \ \ \ \ &\ \ \ \vdots\ \ &\ \ \ \ \ \ \ \ \vdots\\\end{matrix}&&\ \ \ \begin{matrix}\vdots&&\ \ \ \ \ \ \vdots\\\end{matrix}\\\begin{matrix}a_{m1}x_1&a_{m2}x_2&a_{m3}x_3\\\end{matrix}&\ldots&\begin{matrix}a_{mn}x_n&=&b_m\\\end{matrix}\\\end{matrix}
$$


$$
\left[\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{m1}&a_{m2}&a_{m3}\\\end{matrix}&\ldots&a_{mn}\\\end{matrix}\right]\left[\begin{matrix}x_1\\\begin{matrix}x_2\\x_3\\\vdots\\\end{matrix}\\x_n\\\end{matrix}\right]=\left[\begin{matrix}b_1\\\begin{matrix}b_2\\b_3\\\vdots\\\end{matrix}\\b_m\\\end{matrix}\right]
$$


$$
A \bullet x=b	\quad (6.7)
$$

$$
A \cdot x=b	\quad (6.7)
$$


where


$$
A=\left[\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{m1}&a_{m2}&a_{m3}\\\end{matrix}&\ldots&a_{mn}\\\end{matrix}\right];\ \ x=\left[\begin{matrix}x_1\\\begin{matrix}x_2\\x_3\\\vdots\\\end{matrix}\\x_n\\\end{matrix}\right];\ \ b=\left[\begin{matrix}b_1\\\begin{matrix}b_2\\b_3\\\vdots\\\end{matrix}\\b_m\\\end{matrix}\right]
$$


If we multiply $Eqn (6.7)$ by $A^{-1}$ the inverse of $A$.


$$
A^{-1} \cdot A \cdot x = A^{-1} \cdot b
$$


$$
A^{-1} \cdot A = I
$$

$$
I \cdot x = A^{-1} \cdot b
$$


$$
x=A^{-1} \cdot b
$$


and


$$
A^{-1}=\frac{C^T}{\left|A\right|}
$$


where $C^T$ is the transpose of the co-factor of matrix $A$


# Existence and properties of solution


## Existence of solution


$$
A.x=b
$$

$$
x=A^{-1}.b
$$


$$
A^{-1}=\frac{C^T}{\left|A\right|}
$$


Forming an augmented matrix $A_b$.


$$
A_b=[A \ | \ b ]
$$


For a solution to exist for a set of linear equations the following must be true:


1. Determinant of A must not be equal to zero, i.e $\left|A\right|\neq0$.
2. A unique solution exists:
   - $rank\ of\ A=rank\ of\ A_b=n$
3. An infinite number of solutions exist:
   - $rank\ of\ A=rank\ of\ A_b=m<n$
4. No solution exists:
   rank\ A<rank\ A_b


## Other properties of the solution


$$
x=0,\quad A^{-1}=0\ or\ b=0
$$


# Gaussian elimination.


## Algorithm of Gaussian Elimination


Gaussian elimination method converts the combine matrix of A and b, [A|b] to triangular matrix. Then proceed with backward substitution to obtain x.


For a system of linear equations


$$
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1 \\
a_{21}x_1+a_{22}x_2+a_{23}x_3=b_2 \\
a_{31}x_1+a_{32}x_2+a_{33}x_3=b_3
$$


Step 1: Write in matrix form.


$$
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\b_3\\\end{matrix}\right]
$$

$$
A\bullet x=b
$$


Step 2: Arrange matrix $A\ and\ b$ together to form augmented matrix $A_b$.


$$
A_b=\left[A|b\right]
$$

$$
A_b=\left[\begin{matrix}a_{11}&a_{12}&\begin{matrix}a_{13}&|&b_1\\\end{matrix}\\a_{21}&a_{22}&\begin{matrix}a_{23}&|&b_2\\\end{matrix}\\a_{31}&a_{32}&\begin{matrix}a_{33}&|&b_3\\\end{matrix}\\\end{matrix}\right]
$$


Step 3: Using matrix row equivalent operation reduce $A_b$ to triangular matrix $\widetilde{A}_{b}$.


$$
A_b\rightarrow\widetilde{A}_{b}
$$

$$
\left[\begin{matrix}a_{11}&a_{12}&\begin{matrix}a_{13}&|&b_1\\\end{matrix}\\a_{21}&a_{22}&\begin{matrix}a_{23}&|&b_2\\\end{matrix}\\a_{31}&a_{32}&\begin{matrix}a_{33}&|&b_3\\\end{matrix}\\\end{matrix}\right]\rightarrow\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]
$$

$$
\widetilde{M}=\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]
$$


Step 4: Back substitution


$$
\begin{matrix}\begin{matrix}{\widetilde{a}}_{11}x_1&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{12}x_2&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{13}x_3&=&{\widetilde{b}}_1\\\end{matrix}\\&\begin{matrix}{\widetilde{a}}_{22}x_2&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{23}x_3&=&{\widetilde{b}}_2\\\end{matrix}\\&&\begin{matrix}{\widetilde{a}}_{33}x_3&=&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}
$$


$$
x_3 =\frac{{\widetilde{b}}_3} {{\widetilde{a}}_{33}}
$$


$$
x_2 =\frac{{\widetilde{b}}_2-{\widetilde{a}}_{23}x_3} {{\widetilde{a}}_{22}}
$$


$$
x_1 =\frac{{\widetilde{b}}_1-{\widetilde{a}}_{12}x_2-{\widetilde{a}}_{13}x_3} {{\widetilde{a}}_{11}}
$$


# Example 

Solve the set of equations.


$$
\begin{matrix}
3x & -3y & -4z & = & 1 \\
x & -y & -z & = & 2 \\
2x & -y & +4y & = & 3
\end{matrix}
$$


Step 1: Write in matrix form.


$$
A\bullet x=b
$$

$$
\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}1\\2\\3\\\end{matrix}\right]
$$


Step 2: Arrange matrix $A\ and\ b$ together augmented matrix $A_b$.


$$
A_b=\left[A|b\right]
$$

$$
M = A_b=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\1&-1&\begin{matrix}-1&|&2\\\end{matrix}\\2&-1&\begin{matrix}\ \ \ 4&|&3\\\end{matrix}\\\end{matrix}\right]
$$


Step 3: Using matrix row equivalent operation reduce $M$ to triangular matrix $\widetilde{M}$.


$$
A_b \rightarrow \widetilde{A}_b	\ (\widetilde{M})
$$

$$
pivot,\ p=1,\ldots,\ m-1\
$$

$$
i=p+1,\ ...,\ m\ \ \ \
$$


Note:


$$
a_{pp}\neq0
$$

If $a_{pp} = 0$ interchange row with a none-zero pivot column element row.


$$
R_i\ =R_i-\left(R_p\times\ \frac{a_{ip}}{a_{pp}}\right)\ \ \


$$


$$
p=1,...,2
$$

$$
i=2,...,3
$$


Reduce ${\widetilde{A}_b}_{p=1}$


when

$$
p=1; \quad  i=2
$$

$$
a_{pp}=a_{11}=3
$$


$$
R_2\ =R_2-\left(R_1\times\ \frac{a_{21}}{a_{11}}\right)\ \ \


$$

$$
R_2=\left[\begin{matrix}1&-1&\begin{matrix}-1&|&2\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\\end{matrix}\right]\times\frac{1}{3}\right)
$$

$$
=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]
$$


$$
p=1;\quad i=3
$$

$$
R_3\ =R_3-\left(R_1\times\ \frac{a_{31}}{a_{11}}\right)


$$

$$

R_3=\left[\begin{matrix}2&-1&\begin{matrix}4&|&3\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\\end{matrix}\right]\times\frac{2}{3}\right)
$$

$$
=\left[\begin{matrix}0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]
$$


$$
{\widetilde{A}_b}_{p=1}
=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]
$$


Reduce ${\widetilde{A}_b}_{p=2}$


$$
p=2; \quad i=3
$$

$$
a_{pp}=a_{22}=0
$$


Interchange row 2 and 3


$$
{\widetilde{A}_b}_{p=1}=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]
$$


$$
p=2;\quad i=3
$$

$$
a_{pp}=a_{22}=1
$$

$$
R_3\ =R_3-\left(R_2\times\ \frac{a_{32}}{a_{22}}\right)\ \ \
$$

$$
R_3=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]\times\frac{0}{1}\right)
$$

$$
=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]
$$


$$
{\widetilde{A}_b}_{p=2}=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]
$$


Step 4: Back substitution


$$
\begin{matrix}
3x_1 & - & 3x_2 & - & 4x_3 & = & 1 \\
 &   & x_2 & + & 6.67x_3 & = & 2.33 \\
 &   &   &  & 0.33x_3 & = & 1.67 \\
\end{matrix}
$$


$$
x_3 = \frac{1.67}{0.33} = 5.06
$$

$$
x_2 = \frac{2.33-6.67(5.06)}{1} = -31.42
$$

$$
x_1 = \frac{1--3(-31.42)--4(5.06)}{3} = -24.34
$$


## Determinant from Gaussian Elimination


$$
\widetilde{A_b}=\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]
$$


$$
\left|A\right|={(-1)}^k\prod_{i}^{m}{\widetilde{a}}_{ii}={\widetilde{a}}_{11}\times{\widetilde{a}}_{22}\times{\widetilde{a}}_{33}
$$


where $k$ is the number of times rows were interchanged.


From the example above and $Eq (8.34)$


$$
\left|A\right|={(-1)}^1\prod_{i=1}^{m=3}{\widetilde{a}}_{ii}
$$

$$
={(-1)}^1(3\times1\times0.33)=-0.99
$$


# Matrix inverse by elementary matrices, adjoint, and partitioning methods.


## Inverse of a square matrix


Recall the solution to system of linear equation:


$$
A \cdot x=b
$$

$$
x=A^{-1} \cdot b
$$

$$
A^{-1}=\frac{C^T}{\left|A\right|}
$$


To solve Eq (9.3) the inverse of matrix $A$, ${(A}^{-1})$ must be evaluated.


where $C^T$ is the adjoint of matrix $A$, and Adjoint is the transpose of the co-factor of matrix $A$.


## Cofactors


Cofactor of a square matrix is obtained from the determinant of its elements.


$$
\left|A\right|=\left|\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{n1}&a_{n2}&a_{n3}\\\end{matrix}&\ldots&a_{nn}\\\end{matrix}\right|
$$


$$
Cofactor=\left[\begin{matrix}\begin{matrix}\begin{matrix}c_{11}\\c_{21}\\c_{31}\\\end{matrix}&\begin{matrix}c_{12}\\c_{22}\\c_{32}\\\end{matrix}&\begin{matrix}c_{13}\\c_{23}\\c_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}c_{1n}\\c_{2n}\\c_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}c_{n1}&c_{n2}&c_{n3}\\\end{matrix}&\ldots&c_{nn}\\\end{matrix}\right]
$$


where each element of the cofactor is formed from the determinant of its sub-matrix multiplied by element position sign. The element positional sign alternate between plus + and minus -.


Evaluate the cofactor of the matrix $A$ below:


$$
A=\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]
$$


For element $a_{11}=3$;

$$
c_{11}=+\left|\begin{matrix}-1&-1\\-1&4\\\end{matrix}\right|=-5
$$

For element $a_{12}=-3$;

$$
c_{12}=-\left|\begin{matrix}1&-1\\2&4\\\end{matrix}\right|=-6
$$

For element $a_{13}=-4$;

$$
c_{13}=+\left|\begin{matrix}1&-1\\2&-1\\\end{matrix}\right|=1
$$

For element $a_{21}=1$;

$$
c_{21}=-\left|\begin{matrix}-3&-4\\-1&4\\\end{matrix}\right|=16
$$

For element $a_{22}=-1$;

$$
c_{22}=+\left|\begin{matrix}3&-4\\2&4\\\end{matrix}\right|=20
$$

For element $a_{23}=-1$;

$$
c_{23}=-\left|\begin{matrix}3&-3\\2&-1\\\end{matrix}\right|=-3
$$

For element $a_{31}=2$;

$$
c_{31}=+\left|\begin{matrix}-3&-4\\-1&-1\\\end{matrix}\right|=-1
$$

For element $a_{32}=-1$;

$$
c_{32}=-\left|\begin{matrix}3&-4\\1&-1\\\end{matrix}\right|=-1
$$

For element $a_{33}=4$;

$$
c_{13}=+\left|\begin{matrix}3&-3\\1&-1\\\end{matrix}\right|=0
$$


The cofactor form is:


$$
Cofactor\ A=\left[\begin{matrix}-5&-6&1\\16&20&-3\\-1&-1&0\\\end{matrix}\right]
$$


## Adjoint


Adjoint of matrix $A$ is the transpose of the cofactor of $A$.


From $Eq (9.16)$


$$
Adj\ A=C^T\ =\left[\begin{matrix}-5&16&-1\\-6&20&-1\\1&-3&0\\\end{matrix}\right]
$$


$$
A^{-1}=\frac{C^T}{\left|A\right|}
$$

$$
\left|A\right|=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1
$$


Therefore,


$$
A^{-1}=\frac{1}{-1}\left[\begin{matrix}-5&16&-1\\-6&20&-1\\1&-3&0\\\end{matrix}\right]
$$

$$
=\left[\begin{matrix}5&-16&1\\6&-20&1\\-1&3&0\\\end{matrix}\right]
$$


To solve the system linear of equation


$$
x=A^{-1} \cdot b
$$


$$

\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}5&-16&1\\6&-20&1\\-1&3&0\\\end{matrix}\right]\left[\begin{matrix}1\\2\\3\\\end{matrix}\right]
$$

$$
\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}(5\times1)+(-16\times2)+(1\times3)\\(6\times1)+(-20\times2)+(1\times3)\\(-1\times1)+(3\times2)+(0\times3)\\\end{matrix}\right]
$$

$$
=\left[\begin{matrix}-24\\-31\\5\\\end{matrix}\right]
$$


# Eigenvalues and Eigenvectors.


## Eigenvalues


Eigenvalues are characteristic scalar value $(\lambda)$ of a square matrix $A$ that satisfy the $Eq (10.1)$.


$$
Ax=\lambda x
$$


In other to find the eigenvalues, we develop the characteristic equation and solve the characteristic polynomial of matrix $A$.


$$
(A-\lambda I)x=0
$$


To prevent the trivial solution $x\neq0$. Therefore we have the characteristic equation $Eq (10.3)$.


$$
\left|A-\lambda I\right|=0
$$


The solution of $Eq (10.3)$ gives the eigenvalues $\lambda$.


Example 10.1


Find the eigenvalues of the matrix.

$$
A=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]
$$


$$
A-\lambda I=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]-\lambda\left[\begin{matrix}1&0\\0&1\\\end{matrix}\right]
$$

$$
=\left[\begin{matrix}(2-\lambda)&3\\4&(1-\lambda)\\\end{matrix}\right]
$$


$$
\left|A-\lambda I\right|=\left|\begin{matrix}\left(2-\lambda\right)&3\\4&\left(1-\lambda\right)\\\end{matrix}\right|
$$

$$
=\left(2-\lambda\right)\left(1-\lambda\right)-12=2-2\lambda-\lambda+\lambda^2-12
$$


$$
\left|A-\lambda I\right|=\lambda^2-3\lambda-10=0
$$


The solutions to the characteristic polynomial in $Eq (10.6)$


$$

\lambda=-2\ or\ 5
$$

$$
\lambda_1=-2,\quad \lambda_2=5
$$


## Eigenvectors


Each eigenvalues obtained has a corresponding eigenvector or eigenline associated with it.


$$
Ax=\lambda x
$$


Example 10.2


When matrix $A$ is:

$$
A=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]
$$

$$
\lambda_1=-2,\quad \lambda_2=5
$$


For $\lambda_1=-2$

$$
\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]=-2\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]
$$

$$
\begin{matrix}\begin{matrix}2x_1&+\\\end{matrix}&\begin{matrix}3x_2&=\\\end{matrix}\ \ \\\begin{matrix}4x_1&+\\\end{matrix}&\begin{matrix}x_2&=\\\end{matrix}\\\end{matrix}\begin{matrix}{-2x}_1\\{-2x}_2\\\end{matrix}
$$

$$
x_2=-\frac{4}{3}x_1
$$


The eigenvector for $\lambda_1=-2$

$$
x_1=\left[\begin{matrix}k\\-{\frac{4}{3}}k\\\end{matrix}\right]\ and\ the\ smallest:\ x_1=\left[\begin{matrix}1\\-{\frac{4}{3}}\\\end{matrix}\right]
$$


For $\lambda_2=5$


$$
\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]=5\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]
$$

$$

\begin{matrix}\begin{matrix}2x_1&+\\\end{matrix}&\begin{matrix}3x_2&=\\\end{matrix}\ \ \\\begin{matrix}4x_1&+\\\end{matrix}&\begin{matrix}x_2&=\\\end{matrix}\\\end{matrix}\begin{matrix}{5x}_1\\{5x}_2\\\end{matrix}
$$

$$
x_2=x_1
$$


The eigenvector for $\lambda_2=5$

$$
x_2=\left[\begin{matrix}k\\k\\\end{matrix}\right]\ and\ the\ smallest:\ x_2=\left[\begin{matrix}1\\1\\\end{matrix}\right]
$$


# Exercises


### Exercise 3

$$
A=\left(\begin{matrix}1&-1&-1\\0&-2&3\\2&1&5\\\end{matrix}\right)
$$

Find the determinant of A:


In [1]:
import numpy as np

A = np.array(
    [
        [1, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ]
)

np.linalg.det(A)


-227.99999999999986

In [49]:
from sympy import *

A = Matrix(
    [
        [1, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ]
)

A.det()


-228

In [50]:
from sympy import *

A = Matrix(
    [
        [1.0, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ]
)

A.det()


-228.000000000000

### Exercise 4

$$
A . x = b \\
$$

$$
A=  \left(
        \begin{matrix}
            1 & -1 & -1 & 0\\
            0 & -2 & 3 & 2\\
            2 & 1 & 5 & 1\\
            -2 & 1 & -2 & 9\
        \end{matrix}
    \right) \\
b=  \left(
        \begin{matrix}
            4\\
            4\\
            4\\
            4\\
        \end{matrix}
    \right)
$$


In [4]:
import numpy as np

A = np.array(
    [
        [1, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ]
)

b = np.array(
    [
        [4],
        [4],
        [4],
        [4],
    ]
)

x = np.linalg.solve(A, b)

print('x = \n', x)


x = 
 [[ 2.57894737]
 [-1.21052632]
 [-0.21052632]
 [ 1.10526316]]


In [3]:
from sympy import *

a, b, c, d = symbols('a b c d')

linsolve(Matrix((
    [1, -1, -1, 0, 4],
    [0, -2, 3, 2, 4],
    [2, 1, 5, 1, 4],
    [-2, 1, -2, 9, 4])), (a, b, c, d))


{(49/19, -23/19, -4/19, 21/19)}

In [59]:
a = 49/19
b = -23/19
c = -4/19
d = 21/19

a, b, c, d


(2.5789473684210527,
 -1.2105263157894737,
 -0.21052631578947367,
 1.105263157894737)

### Exercise 5

Solve for $x, y, z$ in the augment matrix $M$.

$$
M =  \left(
        \begin{matrix}
            8 & 4 & -1 & 3\\
            1 & 6 & 2 & 3\\
            4 & 0 & 2 & 3\\
        \end{matrix}
    \right)
$$


In [60]:
import numpy as np

A = np.array(
    [
        [8, 4, -1],
        [1, 6, 2],
        [4, 0, 2],
    ]
)

b = np.array(
    [
        [3],
        [3],
        [3],
    ]
)

x = np.linalg.solve(A, b)

print('x = \n', x)


x = 
 [[0.375 ]
 [0.1875]
 [0.75  ]]


In [8]:
from sympy import *

x, y, z = symbols('x y z')

linsolve(Matrix((
    [8, 4, -1, 3],
    [1, 6, 2, 3],
    [4, 0, 2, 3])), (x, y, z))


FiniteSet((3/8, 3/16, 3/4))

In [61]:
x = 3/8
y = 3/16
z = 3/4

x, y, z


(0.375, 0.1875, 0.75)

### Exercise 6

Solve for $x, y, z$ in the augment matrix $M$.

$$
M =  \left(
        \begin{matrix}
            3 & -1 & -1 & 4\\
            4 & -2 & 3 & 2\\
            2 & 1 & -5 & -1\\
        \end{matrix}
    \right)
$$


In [24]:
import numpy as np
from fractions import Fraction

M = np.array(
    [
        [3, -1, -1, 4],
        [4, -2, 3, 2],
        [2, 1, -5, -1],
    ], dtype=float
)

print('M =\n', M)
(m, n) = M.shape
print('mxn =\n', m, 'x', n)
print('|A| = \n', M[:3, :3], '\n =', np.linalg.det(M[:3, :3]))

k = 0
p = 0

for p in range(0, m-1):
    for i in range(p+1, m):
        if M[p, p] == 0:
            # change row
            for j in range(i, m):
                if M[j, p] != 0:
                    k += 1
                    Mp = np.copy(M[p])
                    M[p] = M[j]
                    M[j] = Mp

                    print('Mx =\n', M)
                    break

        M[i] = M[i, :] - M[p, :]*M[i, p]/M[p, p]
        print('M =\n', M)

detA = 1
for p in range(m):
    detA *= M[p, p]

print('|A| =', detA)


M =
 [[ 3. -1. -1.  4.]
 [ 4. -2.  3.  2.]
 [ 2.  1. -5. -1.]]
mxn =
 3 x 4
|A| = 
 [[ 3. -1. -1.]
 [ 4. -2.  3.]
 [ 2.  1. -5.]] 
 = -13.0
M =
 [[ 3.         -1.         -1.          4.        ]
 [ 0.         -0.66666667  4.33333333 -3.33333333]
 [ 2.          1.         -5.         -1.        ]]
M =
 [[ 3.         -1.         -1.          4.        ]
 [ 0.         -0.66666667  4.33333333 -3.33333333]
 [ 0.          1.66666667 -4.33333333 -3.66666667]]
M =
 [[  3.          -1.          -1.           4.        ]
 [  0.          -0.66666667   4.33333333  -3.33333333]
 [  0.           0.           6.5        -12.        ]]
|A| = -12.999999999999995


In [63]:
from sympy import *

x, y, z = symbols('x y z')

linsolve(
    Matrix(
        (
            [3, -1, -1, 4],
            [4, -2, 3, 2],
            [2, 1, -5, -1]
        )
    ),
    (x, y, z)
)


{(-21/13, -7, -24/13)}

In [65]:
from sympy import *
x, y, z = symbols('x y z')

linsolve(Matrix((
    [1, 1, 1, 1],
    [1, 1, 2, 3],
    [1, 0, 2, 3])), (x, y, z))


{(-1, 0, 2)}

# Test 2 Make Up

Consider the system of linear equation below:

$$
\begin{matrix}
3x & - & y & - & 2 & - & z &= & 4 \\
4z & - & 2y & + & 3x & + & y & = & 2 \\
2x & + & y & - & 5y & - & 1 & + & z & + & x & = & -1 \\
\end{matrix}


$$

Q1.  
 Write the matrices form. $A\bullet x=b$  
 What is the order of matrix $A$  
 What is the order of matrix $b$.  
 Determinant of matrix $A$  
 Rank of $A$

Q2.
Write the augment matrix $A_b$, $A_b=\left[A|b\right]$  
 What is the order of matrix $A_b$.  
 Solve the system of linear equation using Gaussian Elimination.


In [6]:
import numpy as np

A = np.array(
    [
        [3.0, -1., -1.],
        [3., -1., 4.],
        [2., -4., 1.],
    ]
)

b = np.array(
    [
        [6.0],
        [2.0],
        [0.0],
    ]
)

x = np.linalg.solve(A, b)
print('x = \n', x)

d = np.linalg.det(A)
print('det(A) = ', d)


x = 
 [[ 2. ]
 [ 0.8]
 [-0.8]]
det(A) =  50.000000000000014


In [7]:
from sympy import *
x, y, z = symbols('x y z')

linsolve(Matrix((
    [3.0, -1., -1., 6.0],
    [3., -1., 4., 2.0],
    [2., -4., 1., 0],
)), (x, y, z))


FiniteSet((2.0, 0.8, -0.8))