In [24]:
import numpy as np

A = np.array(
    [
    [-1, 2, -3]
    ], dtype=float
)

(m,n) = np.shape(A)

print('order of \n', A, '= ', f'{m} x {n}')

order of 
 [[-1.  2. -3.]] =  1 x 3


In [21]:
columns = 5
rows = 15

m = rows
n = columns

print('order = ', f'{m} x {n}')

order =  15 x 5


In [23]:
import numpy as np

A = np.array(
    [
        [1, -1, -1],
        [0, -2, 3],
        [2, 1, 5],
    ], dtype=float
)

B = np.array(
    [
        [1, 1, 1],
        [1, 1, 1],
    ], dtype=float
)

try:
    print('A*B=\n', A * B)
except ValueError:
    print('A*B=\nError multiplying A*B')

print()

try:
    print('B*A=\n', B @ A)
except ValueError:
    print('B*A=\nError multiplying B*A')

print()

try:
    print('A*B^T=\n', A @ np.transpose(B))
except ValueError:
    print('A*B^T=\nError multiplying A*B^T')

print()

try:
    print('B*A^T=\n', B @ np.transpose(A))
except ValueError:
    print('B*A^T=\nError multiplying B*A^T=')


A*B=
Error multiplying A*B

B*A=
 [[ 3. -2.  7.]
 [ 3. -2.  7.]]

A*B^T=
 [[-1. -1.]
 [ 1.  1.]
 [ 8.  8.]]

B*A^T=
 [[-1.  1.  8.]
 [-1.  1.  8.]]


In [26]:
import numpy as np

A = np.array(
    [
        [1, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ], dtype=float
)

np.linalg.det(A)

-227.99999999999986

In [27]:
import numpy as np

A = np.array(
    [
        [1, -1, -1, 0],
        [0, -2, 3, 2],
        [2, 1, 5, 1],
        [-2, 1, -2, 9],
    ]
)

b = np.array(
    [
        [4],
        [4],
        [4],
        [4],
    ]
)

x = np.linalg.solve(A,b)

print('x = \n', x)


x = 
 [[ 2.57894737]
 [-1.21052632]
 [-0.21052632]
 [ 1.10526316]]


In [29]:
from sympy import *

x,y,z=symbols('x y z')

linsolve(
    Matrix(
        (
            [3, -1, -1, 4],
            [4, -2, 3, 2],
            [2, 1, -5, -1]
        )
    ), 
    (x, y, z)
)


FiniteSet((-21/13, -7, -24/13))

In [28]:
import numpy as np
from fractions import Fraction

M = np.array(
    [
        [3, -1, -1, 4],
        [4, -2, 3, 2],
        [2, 1, -5, -1],
    ],dtype=float
)

print('M =\n', M)
(m,n) = M.shape
print('mxn =\n', m, 'x', n)
print('|A| = \n', M[:3,:3], '\n =', np.linalg.det(M[:3,:3]))

k = 0
p = 0

for p in range(0,m-1):
    for i in range(p+1,m):
        if M[p,p] == 0:
            # change row
            for j in range(i,m):
                if M[j,p] != 0:
                    k += 1
                    Mp = np.copy(M[p])
                    M[p] = M[j]
                    M[j] = Mp

                    print('Mx =\n', M)
                    break

        M[i] = M[i,:] - M[p,:]*M[i,p]/M[p,p]
        print('M =\n', M)

detA = 1
for p in range(m):
    detA *= M[p,p]

print('|A| =', detA)


M =
 [[ 3. -1. -1.  4.]
 [ 4. -2.  3.  2.]
 [ 2.  1. -5. -1.]]
mxn =
 3 x 4
|A| = 
 [[ 3. -1. -1.]
 [ 4. -2.  3.]
 [ 2.  1. -5.]] 
 = -13.0
M =
 [[ 3.         -1.         -1.          4.        ]
 [ 0.         -0.66666667  4.33333333 -3.33333333]
 [ 2.          1.         -5.         -1.        ]]
M =
 [[ 3.         -1.         -1.          4.        ]
 [ 0.         -0.66666667  4.33333333 -3.33333333]
 [ 0.          1.66666667 -4.33333333 -3.66666667]]
M =
 [[  3.          -1.          -1.           4.        ]
 [  0.          -0.66666667   4.33333333  -3.33333333]
 [  0.           0.           6.5        -12.        ]]
|A| = -12.999999999999995


$$
\left[
    \begin{matrix}
        (1-\alpha_{11k}) & -\alpha_{12k} & -\alpha_{13k} & -\alpha_{14k} & -\alpha_{15k} & -\alpha_{16k} & -\alpha_{17k} & -\alpha_{18k} & -\alpha_{19k} & -\alpha_{110k} \\
        
    \end{matrix}
\right]
$$  

$$
\left[
    \begin{matrix}
        (1-\alpha_{11k}) & -\alpha_{12k} & -\alpha_{13k} & -\alpha_{14k} & -\alpha_{15k} & -\alpha_{16k} & -\alpha_{17k} & -\alpha_{18k} & -\alpha_{19k} & -\alpha_{110k} \\
        -\alpha_{21k} & (1-\alpha_{21k}) & -\alpha_{23k} & -\alpha_{24k} & -\alpha_{25k} & -\alpha_{26k} & -\alpha_{27k} & -\alpha_{28k} & -\alpha_{29k} & -\alpha_{210k} \\
        -\alpha_{31k} & -\alpha_{31k} & (1-\alpha_{33k}) & -\alpha_{34k} & -\alpha_{35k} & -\alpha_{36k} & -\alpha_{37k} & -\alpha_{38k} & -\alpha_{39k} & -\alpha_{310k} \\
        -\alpha_{41k} & (1-\alpha_{41k}) & -\alpha_{43k} & (1-\alpha_{44k}) & -\alpha_{45k} & -\alpha_{46k} & -\alpha_{47k} & -\alpha_{48k} & -\alpha_{49k} & -\alpha_{410k} \\
        
    \end{matrix}
\right]
$$  

In [1]:
from sympy import *

a, b, c = symbols('a b c')

linsolve(Matrix((
        [3, -1, -1, 6],
        [3, -1, 4, 2],
        [3, -4, 1, 0],
        )), (a,b,c))

FiniteSet((20/9, 22/15, -4/5))